### ISSUE TITLE
Review the orchestration code to be less chatty

### ISSUE THREAD

**Issue by akshaya-a** [dask/dask-cloudprovider#105]
run.status vs run.get_status() # fetches latest - don't use the latter multiple times in a conditional

also let's look into a better way to signal cluster standup than the metric name "scheduler", which can also be a bit more efficient as is by passing the metric name into the query

 def get_metrics(self, name=None, ...

**Comment by FredFLi** [comment]
Not sure there is better signal there. "scheduler" availability is the only signal we need as we have to make sure the scheduler is ready before proceeding.
