### ISSUE TITLE
Instantiating a FargateCluster when more than 50 log groups present fails if dask-ecs is > 50 in list of log groups

### ISSUE THREAD

**Issue by gdesmarais-ctx** [dask/dask-cloudprovider#111]
If you already have a log group named `dask-ecs` and it is not one of the first 50 log groups, the following call fails:

**What happened**:

A `ResourceAlreadyExistsException` exception is raised when instantiating a `FargateCluster`

**What you expected to happen**:

The `FargetCluster` instance is created

**Minimal Complete Verifiable Example**:

```python
from dask_cloudprovider.providers.aws.ecs import FargateCluster
fc = FargateCluster(vpc='vpc-nnnnnnn')
```

**Anything else we need to know?**:

The exception given is (first traceback is relevant one):

```
Traceback (most recent call last):
  File "/Users/gdesmarais/git/rightsize/rightsize-venv/lib/python3.7/site-packages/distributed/utils.py", line 323, in f
    result[0] = yield future
  File "/Users/gdesmarais/git/rightsize/rightsize-venv/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Users/gdesmarais/git/rightsize/rightsize-venv/lib/python3.7/site-packages/dask_cloudprovider/providers/aws/ecs.py", line 771, in _start
    or await self._create_cloudwatch_logs_group()
  File "/Users/gdesmarais/git/rightsize/rightsize-venv/lib/python3.7/site-packages/dask_cloudprovider/providers/aws/ecs.py", line 961, in _create_cloudwatch_logs_group
    await logs.create_log_group(logGroupName=log_group_name, tags=self.tags)
  File "/Users/gdesmarais/git/rightsize/rightsize-venv/lib/python3.7/site-packages/aiobotocore/client.py", line 134, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceAlreadyExistsException: An error occurred (ResourceAlreadyExistsException) when calling the CreateLogGroup operation: The specified log group already exists
distributed.deploy.spec - WARNING - Cluster closed without starting up
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/gdesmarais/git/rightsize/rightsize-venv/lib/python3.7/site-packages/distributed/deploy/spec.py", line 621, in close_clusters
    cluster.close(timeout=10)
  File "/Users/gdesmarais/git/rightsize/rightsize-venv/lib/python3.7/site-packages/distributed/deploy/cluster.py", line 84, in close
    return self.sync(self._close, callback_timeout=timeout)
  File "/Users/gdesmarais/git/rightsize/rightsize-venv/lib/python3.7/site-packages/distributed/deploy/cluster.py", line 163, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/Users/gdesmarais/git/rightsize/rightsize-venv/lib/python3.7/site-packages/distributed/utils.py", line 339, in sync
    raise exc.with_traceback(tb)
  File "/Users/gdesmarais/git/rightsize/rightsize-venv/lib/python3.7/site-packages/distributed/utils.py", line 323, in f
    result[0] = yield future
  File "/Users/gdesmarais/git/rightsize/rightsize-venv/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Users/gdesmarais/git/rightsize/rightsize-venv/lib/python3.7/site-packages/distributed/deploy/spec.py", line 391, in _close
    await self.scheduler.close()
AttributeError: 'FargateCluster' object has no attribute 'scheduler'
```

This is because the call to `logs.describe_log_groups()` in `dask_cloudprovider.providers.aws.ecs.ECSCluster._create_cloudwatch_logs_group` does not follow the returned `nextToken` for paged responses.

An implementation  such as:
```
    async def _create_cloudwatch_logs_group(self):
        log_group_name = "dask-ecs"
        async with self._client("logs") as logs:
            groups = (await logs.describe_log_groups())
            log_group_defs = groups["logGroups"]
            while groups.get("nextToken"):
                groups = (await logs.describe_log_groups(nextToken=groups["nextToken"]))
                log_group_defs.extend(groups["logGroups"])

            if log_group_name not in [
                group["logGroupName"]
                for group in log_group_defs
            ]:
                await logs.create_log_group(logGroupName=log_group_name, tags=self.tags)
                await logs.put_retention_policy(
                    logGroupName=log_group_name,
                    retentionInDays=self._cloudwatch_logs_default_retention,
                )
        # Note: Not cleaning up the logs here as they may be useful after the cluster is destroyed
        return log_group_name
```

would address the issue.

It also seems like it would be valuable to allow a kwarg param to ECSCluster for `log_group_name`.

**Environment**:

- Dask version:  2.19.0
- Python version: 3.7.7
- Operating System: macOS Catalina (Version 10.15.5)
- Install method (conda, pip, source): pip

**Comment by jacobtomlinson** [comment]
Thanks for raising this and thanks for the code snippet to fix this, do you feel you could raise a PR with this change?

> It also seems like it would be valuable to allow a kwarg param to ECSCluster for log_group_name.

We already have this. The kwarg is `cloudwatch_logs_group`.

https://cloudprovider.dask.org/en/latest/api.html#dask_cloudprovider.ECSCluster

**Comment by gdesmarais-ctx** [comment]
> Thanks for raising this and thanks for the code snippet to fix this, do you feel you could raise a PR with this change?
> 
> > It also seems like it would be valuable to allow a kwarg param to ECSCluster for log_group_name.
> 
> We already have this. The kwarg is `cloudwatch_logs_group`.
> 
> https://cloudprovider.dask.org/en/latest/api.html#dask_cloudprovider.ECSCluster

But the param isn't respected in the `_create_cloudwatch_logs_group `.  This is my first time on this repo, so I wanted to ask a couple of convention issues:

1. Do you want different PRs for the 'repect the cloudwatch_logs_group' and this issue, or you guys ok with some messiness in the PRs?
2. Any conventions you need on naming (PRs, branches, etc?)

**Comment by jacobtomlinson** [comment]
> Do you want different PRs for the 'repect the cloudwatch_logs_group' and this issue, or you guys ok with some messiness in the PRs?

Would prefer separate PRs for things which are separate. This is entangled enough that one would probably be fine.

> Any conventions you need on naming (PRs, branches, etc?)

No preference. We will squash on merge and most likely change the title anyway.

**Comment by gdesmarais-ctx** [comment]
@jacobtomlinson - I think the logs option warrants more thought than I have given it.  If it is ok with you, I'm not going to shove it into this pr.
