### ISSUE TITLE
Unable to connect to scheduler on Fargate

### ISSUE THREAD

**Issue by srib** [dask/dask-cloudprovider#112]
**What happened**:
`OSError` on trying to connect to 'tcp://10.14.52.173:8786' after 10 s: connect() didn't finish in time while launching a `FargateCluster`.

**What you expected to happen**:
Expected the workers to connect to a `FargateCluster`. 

**Minimal Complete Verifiable Example**:

```python
from dask_cloudprovider import FargateCluster 

cluster_name_template = 'dask-scheduler-dev'

cloudwatch_logs_group = 'dask-ecs-appname-dev'

vpc = 'VPC_STRING_HERE' 

subnets = [LIST_OF_SUBNETS]

security_groups = ['SECURITY_GROUP']

cluster = FargateCluster(scheduler_timeout = '30 minutes',
                         platform_version = 'LATEST',
                         cluster_name_template=cluster_name_template,
                         cloudwatch_logs_group=cloudwatch_logs_group,
                         vpc=vpc,
                         subnets=subnets,
                         security_groups=security_groups,
                         find_address_timeout = 600, 
                         fargate_use_private_ip=True,
                         skip_cleanup = True)
```

**Anything else we need to know?**:
I am trying to run this from a CI system (CodeBuild on AWS). 

**Environment**:

- Dask version: `2.20.0` - using the latest Docker image
- Python version: 3.7.7
- Operating System: Ubuntu 18.04
- Install method (conda, pip, source): conda

**Comment by jacobtomlinson** [comment]
Is your codebuild pipeline in the same VPC and does it have routing through to the correct subnet?

**Comment by srib** [comment]
Sorry, I found the issue. It was the VPC and the subnet that was causing the problem. Thanks!
