### ISSUE TITLE
AzureML Provider : Issues with resource group while creating AML Compute

### ISSUE THREAD

**Issue by arnabbiswas1** [dask/dask-cloudprovider#116]
While using the Azure ML Provider using the latest 0.4.0 package from [pypi](https://pypi.org/project/dask-cloudprovider/), I encountered with the following issues:

1. Not necessarily the resource group of the AML Workspace and the VNET would always be the same. If those are different, then compute cluster creation is failing while mounting the data store. The following code assumes that if VNET and SUBNET values are passed, then resource group will be same as the resource group of the AML workspace which is not correct.

```
        if self.vnet and self.subnet:
            vnet_rg = self.workspace.resource_group
            vnet_name = self.vnet
            subnet_name = self.subnet
```

IMHO following should do. If the resource_group is explicitly passed use it, otherwise, use the resource group associated with ML workspace.
```
	if self.vnet and self.subnet:
            vnet_name = self.vnet
            subnet_name = self.subnet
	    if self.resource_group:
	    	vnet_rg = self.resource_group
	    else:
	    	vnet_rg = self.workspace.resource_group
```

2. Initially I was creating the AML resource using the following code (using Jupyter Lab from Compute Instances):
```
		amlcluster = AzureMLCluster(ws,
                            vm_size="STANDARD_DS13_V2", 
                            datastores=[Datastore.get(ws, "my_datastore")], 
                            environment_definition=ws.environments['AzureML-Dask-CPU'], 
                            initial_node_count=1, 
                            scheduler_idle_timeout=600)
```
This was failing while mounting the datastore with the following error message (since I didn't configure VNET as mentioned in #1):

> ERROR - Failed to start the AzureML cluster. {'error': {'code': 'UserError', 'message': 'AzureMLCompute job failed.\nBFSMountError: unable to mount blob fuse file system\n\tInfo: Could not mount Azure Blob Container some_name at my_datastore: Unauthorized. Cannot access the storage account with the given account key. Please verify that the account key is valid.\n\tInfo: Job environment preparation failed on 10.0.0.5.', 'details': []}, 'correlation': {'operation': None, 'request': 'aaaa'}, 'environment': 'aaa', 'location': 'aaa', 'time': '2020-07-30T00:00:00.00000'}
> NoneType: None

But by the time it fails, the physical compute cluster with 1 node has already been created. Since it failed, amlcluster object was not created and as a result I am not able to clean the compute cluster using:

```
    amlcluster.close()
````

As expected, resulting error message: 

> NameError: name 'amlcluster' is not defined

Although, I can clean the cluster from the AML UI, ideally, any failure should be handled gracefully and should delete the physical resource.

3. Documentation for vnet, subnet is not present. Someone need to read the source code to discover those options.

4. Documentation for 'datastores' describes it as a list of strings. But, for me list of `azureml.data.azure_storage_datastore.AzureBlobDatastore` worked (i.e. `[Datastore.get(ws, "my_datastore")]`). Probably it would be better if the documentation is improved.
```
    datastores: List[str] (optional)
        List of Azure ML Datastores to be mounted on the headnode -
        see https://aka.ms/azureml/data and https://aka.ms/azureml/datastores.

        Defaults to ``[]``. To mount all datastores in the workspace,
        set to ``ws.datastores.values()``.

```

**Comment by jacobtomlinson** [comment]
Looks like there are two things to do here:

1. Allow explicit passing of the resource group
1. Handle cleanup on failed creation

@arnabbiswas1 as you proposed a solution would you be able to submit a PR for 1.?
@lostmygithubaccount would you be able to look at 2.?

**Comment by arnabbiswas1** [comment]
@jacobtomlinson Yes I can take care of #1. Thanks for the opportunity.

**Comment by lostmygithubaccount** [comment]
@drabastomek will look into #2 at some point

**Comment by lostmygithubaccount** [comment]
should be fixed by: https://github.com/dask/dask-cloudprovider/pull/123
