### ISSUE TITLE
Build is failing while executing flake8 command

### ISSUE THREAD

**Issue by arnabbiswas1** [dask/dask-cloudprovider#118]
dask-cloudprovider build is failing with  error while executing the following:

> #!/bin/bash -eo pipefail
> /home/circleci/miniconda/envs/dask-cloudprovider-test/bin/flake8 dask-cloudprovider
> /home/circleci/miniconda/envs/dask-cloudprovider-test/bin/black --check dask_cloudprovider setup.py

Here is the error message:

> dask-cloudprovider:0:1: E902 FileNotFoundError: [Errno 2] No such file or directory: 'dask-cloudprovider'
> 
> Exited with code exit status 1

And [here](https://app.circleci.com/pipelines/github/dask/dask-cloudprovider/194/workflows/252628a3-feae-4772-a9b5-048ba41d7f3a/jobs/190) is the build failing build.

**Comment by jacobtomlinson** [comment]
Thanks for raising this @arnabbiswas1
