### ISSUE TITLE
Add ability to specify task definitions for scheduler and workers

### ISSUE THREAD

**Issue by awoods91** [dask/dask-cloudprovider#135]
From the code in ecs.py, I see that the task definitions for both schedulers and workers are created on the fly during cluster creation:

        self.scheduler_task_definition_arn = (
            await self._create_scheduler_task_definition_arn()
        )
        self.worker_task_definition_arn = (
            await self._create_worker_task_definition_arn()
        )

Would it be possible to specify both the scheduler/worker task definitions during the function call for creating the Fargate or ECS cluster?

**Comment by jacobtomlinson** [comment]
Sure I see no reason why not. Would you be interested in raising a PR to add this?

**Comment by awoods91** [comment]
Hey Jacob - I'd be very interested. I'll try and get a PR out ASAP.
