### ISSUE TITLE
API docs are broken

### ISSUE THREAD

**Issue by jcrist** [dask/dask-cloudprovider#136]
The current docs build has broken api docs, no information is provided on any of the classes:

<img width="761" alt="Screen Shot 2020-09-16 at 2 58 35 PM" src="https://user-images.githubusercontent.com/2783717/93386350-32ef9400-f82d-11ea-9a67-87ed56dc5043.png">

**Comment by jacobtomlinson** [comment]
Thanks @jcrist I'll take a look
