### ISSUE TITLE
Restructure imports

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-cloudprovider#139]
Recently we made cloud provider dependencies optional, so for example if you want to use the AzureML cluster manager you need to `pip install dask-cloudprovide[azure]`.

If the Azure dependencies are missing we raise an `ImportError` with info on how to install these dependencies.

However the `AzureMLCluster` is imported at the root of the package, and to ensure that `import dask_cloudprovider` still works we catch the `ImportError` and supress it. So if a user runs `from dask_cloudprovider.providers.azure.azureml import AzureMLCluster` they will see the correct error, but if they call `from dask_cloudprovider import AzureMLCluster` they will get an attribute error.

To resolve this I propose we restructure the imports to make them more pleasant. Each provider should have a submodule under the root module and users should import cluster managers from there. The top level package will not expose those cluster managers. This allows us to group optional dependencies within a submodule.

Eg

```python
from dask_cloudprovider.aws import FargateCluster

from dask_cloudprovider.azure import AzureMLCluster
```

### Deprecations

This means that `from dask_cloudprovider import FargateCluster` will now always give an attribute error. It would be really nice to find a way to catch this and show a deprecation error with instructions on how to correct import the class.

I'm not sure how to do this, so input would be appreciated.

**Comment by jorisvandenbossche** [comment]
With Python 3.7+, you can continue providing the same experience (available at the top-level) and at the same time provide a better error message when it is not available by defining a module level `__getattr__` (where you can raise a custom ImportError instead of the default AttributeError). I did something similar for the `pyarrow.fs` package: https://github.com/apache/arrow/blob/1f30466ac7042354de35cc69fd49ced1acd54b38/python/pyarrow/fs.py#L39-L64

**Comment by jacobtomlinson** [comment]
Thanks @jorisvandenbossche that's awesome I wasn't aware of that.

I think today we still support Python 3.6, but there are discussions to drop it here dask/community#66.

**Comment by jorisvandenbossche** [comment]
You actually don't *need* your package to be 3.7+, you can still use it anyway. But users will only get the improved error message when they are using 3.7+, and if they are using 3.6, they still get the same confusing error message as it is now (so even with that it can be a net plus, I would say)

**Comment by jacobtomlinson** [comment]
This was discussed in the Dask weekly meeting and the general consensus was for `dask-cloudprovider` to drop 3.6 in order to implement this.

Thanks again for the tip @jorisvandenbossche.

**Comment by jacobtomlinson** [comment]
> they still get the same confusing error message as it is now (so even with that it can be a net plus, I would say)

Ah fair enough!
