### ISSUE TITLE
Docs don't quite seem sufficient for Azure

### ISSUE THREAD

**Issue by nickeubank** [dask/dask-cloudprovider#140]
Trying to get dask up on azureml, and finding a few problems:

- conda-forge only seems to be serving up v0.2, so probably shouldn't be listed
- When I do what the docs suggest from my local computer, I get the following: 

![image](https://user-images.githubusercontent.com/9683693/95025205-138e9e80-0656-11eb-8a13-31a99953d859.png)

That `tcp://localhost:9002` link is not something I can drop in a browser, so I'm wondering: how do I now connect to this cluster? 

If I just look at object, don't print, I get:

![image](https://user-images.githubusercontent.com/9683693/95025390-73397980-0657-11eb-8bf9-1ed237391b02.png)

**Comment by nickeubank** [comment]
running the following, if helpful:

```
amlcluster = AzureMLCluster(ws,
                            vm_size="STANDARD_DS13_V2",                                 # Azure VM size for the Compute Target
                            datastores=ws.datastores.values(),                          # Azure ML Datastores to mount on the headnode
                            environment_definition=ws.environments['AzureML-Dask-CPU'], # Azure ML Environment to run on the cluster
                            jupyter=True,                                               # Flag to start JupyterLab session on the headnode
                            initial_node_count=2,                                       # number of nodes to start
                            scheduler_idle_timeout=7200                                 # scheduler idle timeout in seconds
                           )
```

**Comment by lostmygithubaccount** [comment]
the widget is not properly rendering, instead you're seeing the `VBox` output. I'm not sure why it's not rendering, might be missing a dependency.

you can get the dashboard link with `print(amlcluster.dashboard_link)`

**Comment by nickeubank** [comment]
aha -- had to enable jupyter extension. I'll make a PR to add that to docs. 

But I still get a `localhost` link -- do I need to do port-forwarding myself?

**Comment by lostmygithubaccount** [comment]
you should be able to paste that localhost link into your browser to view the Dask dashboard. To connect to the cluster, you do not need to do port-forwarding yourself - you have two options:

1. simply create a Dask Client with the Cluster
1. open the JupyterLab session running on the Cluster (if `jupyter=True`) and connect to Dask Client locally

For the first:

```python
from dask.distributed import Client

c = Client(amlcluster)
# dask operations will now execute on the cluster via this client 
```

For the second:

```python
print(amlcluster.jupyter_link)
```

follow this link - should open a JupyterLab session running on the headnode of the cluster - you're in an Azure ML Run, which can be used to retrieve the IP:port of the scheduler. In a cell in this sesion, run:

```python
from azureml.core import Run
from dask.distributed import Client 

run = Run.get_context()
c = Client(run.get_metrics()["scheduler"])
```

**Comment by nickeubank** [comment]
AMAZING. Thank you so much!
