### ISSUE TITLE
conda-forge serving version 0.2

### ISSUE THREAD

**Issue by nickeubank** [dask/dask-cloudprovider#143]
This an issue for this repo, or conda-forge?

https://anaconda.org/conda-forge/dask-cloudprovider

**Comment by jacobtomlinson** [comment]
We are currently blocked on an AzureML dependency issue. @lostmygithubaccount do you know if there has been any progress on that?

**Comment by lostmygithubaccount** [comment]
#144 will remove the dependency on `azureml-train`, leaving only `azureml-core`, which I also don't think is on conda but **should** be simple enough to get there

@bandsina what would it take to get `azureml-core` on conda-forge?

**Comment by rpanai** [comment]
Hi, still not new versions [PR](https://github.com/conda-forge/dask-cloudprovider-feedstock/pulls). Have you already considered write a new recipe and upload it? I could give a help here.

**Comment by rpanai** [comment]
@lostmygithubaccount  I tried to build a recipe for azureml-core but I get the following error:
```
Error: No source urls found for azureml-core
```

**Comment by jacobtomlinson** [comment]
As of the import refactor in #153 we could now release to Conda Forge without the AzureML dependency. All other cluster managers would work as expected and the `dask_cloudprovider.azure.AzureMLCluster` would raise an import error asking the user to run `pip install dask_cloudprovider[azure]`.

This could be an acceptable workaround until the AzureML packages are made available on Conda Forge. Once they are we can just update our recipe with the new dependencies and the import error would go away.

**Comment by jacobtomlinson** [comment]
Latest version now on conda-forge
