### ISSUE TITLE
Timeout when creating Dask cluster on Azure ML

### ISSUE THREAD

**Issue by Nathan2Warren** [dask/dask-cloudprovider#148]
I have attempted to create a Dask cluster on Azure ML using the following API.

```
amlcluster = AzureMLCluster(
    ws,
    vm_size="STANDARD_DS11_V2", 
    datastores=ws.datastores.values(),  
    environment_definition=ws.environments[
       "AzureML-Dask-CPU"
    ],  
    jupyter=True,  
    initial_node_count=1, 
    scheduler_idle_timeout=7200 
)
```
While the cluster is being created, I see it on Azure Machine Learning successfully establishing a node. The code continues to run/hang until a timeout occurs and the cluster shuts down and I receive this error. 

> ERROR - in <closed TCP>: ConnectionResetError: [Errno 54] Connection reset by peer
> Traceback (most recent call last):
>   File "/Users/N1/opt/anaconda3/lib/python3.8/site-packages/distributed/comm/tcp.py", line 186, in read
>     lengths = await stream.read_bytes(8 * n_frames)
> tornado.iostream.StreamClosedError: Stream is closed
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/N1/opt/anaconda3/lib/python3.8/site-packages/dask_cloudprovider/providers/azure/azureml.py", line 612, in __create_cluster
>     await super()._start()
>   File "/Users/N1/opt/anaconda3/lib/python3.8/site-packages/distributed/deploy/cluster.py", line 64, in _start
>     self.scheduler_info = await comm.read()
>   File "/Users/N1/opt/anaconda3/lib/python3.8/site-packages/distributed/comm/tcp.py", line 199, in read
>     convert_stream_closed_error(self, e)
>   File "/Users/N1/opt/anaconda3/lib/python3.8/site-packages/distributed/comm/tcp.py", line 121, in convert_stream_closed_error
>     raise CommClosedError("in %s: %s: %s" % (obj, exc.__class__.__name__, exc))
> distributed.comm.core.CommClosedError: in <closed TCP>: ConnectionResetError: [Errno 54] Connection reset by peer

Using the exact same code, I was able to create a cluster using a virtual container provided by my school, but I am unable to run it locally. My firewall was off while trying to create the cluster. 

**Environment**:
I reinstalled my python via anaconda 2 days ago (10/20/20) and since then have only installed the following packages with pip: 
```
azure-storage-blob == 12.5.0
azureml-sdk == 1.14.0                         
dask_cloudprovider == 0.4.1
ipywidgets == 7.5.1
```

- Python version: 3.8.3
- Operating System: macOS Catalina (10.15.2)
- Install method: pip

**Comment by jacobtomlinson** [comment]
cc @lostmygithubaccount

**Comment by Nathan2Warren** [comment]
My local started working after using `conda install adlfs`. Somehow this altered the previously installed packages.
