### ISSUE TITLE
AzureMLCluster ignoring `initial_node_count`?

### ISSUE THREAD

**Issue by nickeubank** [dask/dask-cloudprovider#150]
I'm finding that when I use AzureMLCluster, Azure is ignoring my `initial_node_count` and always giving me 1 node?

**Comment by lostmygithubaccount** [comment]
can you double check that there are no typos in your code? 

the cluster will return once it has 1 node and the scheduler up and running, while the scaling happens in the background - this can take some time. can you check your compute target in the web ui to see if it is trying to scale up, and if there are any error messages like quota etc? 

I set `initial_node_count=60` in this example without issue: https://github.com/Azure/azureml-examples/blob/main/tutorials/using-dask/2.eds-at-scale.ipynb

**Comment by nickeubank** [comment]
ah, ok. yeah, maybe I'm looking for results too fast. Will try again.

**Comment by nickeubank** [comment]
You got it. 

BTW: @lostmygithubaccount could you link to those tutorials on the `dask-cloudprovider` docs page? I hadn't seen those.
