### ISSUE TITLE
Generic Azure support

### ISSUE THREAD

**Issue by lostmygithubaccount** [dask/dask-cloudprovider#154]
With the new VMCluster and GCP support being added, what would it take to add a generic Azure cloudprovider package?

**Comment by quasiben** [comment]
Generally, not much.   You will need to add methods to create and destroy a VM.  It's also worth noting that VMCluster assumes that the instances launches with cloud-init support.

**Comment by mrocklin** [comment]
I would love to see generic azure support here

**Comment by jacobtomlinson** [comment]
Yeah this would be great. I'm happy to start taking a look. Perhaps once I have something working I can push it up and get a review from @lostmygithubaccount.

**Comment by mrocklin** [comment]
I'm curious, Cody, do you have a sense for what the spinup time for a VM is
on Azure?

**Comment by lostmygithubaccount** [comment]
just tried this, took <60s

![image](https://user-images.githubusercontent.com/54814569/98392626-15f56700-200d-11eb-8e33-d8e08b7acdb8.png)

@jacobtomlinson would be great if you could start, I'm happy to contribute and help where I can

**Comment by lostmygithubaccount** [comment]
Create an Ubuntu Linux VM using a cloud-init script for configuration. See: https://docs.microsoft.com/azure/virtual-machines/virtual-machines-linux-using-cloud-init

**Comment by jacobtomlinson** [comment]
Great thanks @lostmygithubaccount. I also found this example which will be helpful.

https://github.com/Azure-Samples/virtual-machines-python-manage/blob/master/example.py

**Comment by lostmygithubaccount** [comment]
@jacobtomlinson do you have any idea of timeline when you could get something started?

**Comment by jacobtomlinson** [comment]
I started to play around with some code last week, but haven't made enough progress to push anything yet. Will likely continue with it this week.

**Comment by mrocklin** [comment]
Whoa, that was fast

**Comment by jacobtomlinson** [comment]
Once you've done it three times the forth comes a little quicker 😁
