### ISSUE TITLE
Read The Docs domain

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-cloudprovider#17]
I've emailed Read The Docs asking them to change the docs slug from `dask-cloud` to `dask-cloudprovider` to align with this repo. Waiting to hear back

Would also be nice to put the docs at cloudprovider.dask.org. 

How do I go about that @mrocklin @jcrist?

**Comment by mrocklin** [comment]
In the past I've created a new RTD project and removed the other one.  That might be a decent alternative if the RTD folks are busy.

Historically NumFOCUS has handled the domain for us.  I believe that @quasiben now has access to the domain through cloudflare.

**Comment by quasiben** [comment]
Once the RTD site is established I think I can help with establishing  cloudprovider.dask.org

**Comment by jacobtomlinson** [comment]
@quasiben Ok it is now at dask-cloudprovider.readthedocs.io. If you could help with the domain that would be great.

**Comment by quasiben** [comment]
http://cloudprovider.dask.org/ is now an alias of readthedocs.io.  I think we now need to do something in readthedocs:

> Add your desired domain in the Read the Docs dashboard for your project (under Your Project >> Admin >> Domains)

https://docs.readthedocs.io/en/stable/custom_domains.html 

Is that right ?

**Comment by jacobtomlinson** [comment]
Awesome stuff! That's all done. Thanks for your help.

![image](https://user-images.githubusercontent.com/1610850/62546614-b7669980-b85b-11e9-8b4d-edd6635c1e77.png)
