### ISSUE TITLE
Microsoft Azure provider creates all VMs in series resulting in long wait times for larger clusters.

### ISSUE THREAD

**Issue by tam203** [dask/dask-cloudprovider#187]
**What happened**:

When creating a cluster with `AzureVMCluster` takes overly long when using multiple workers because each VM is created in series, first the scheduler... then one worker... then the next... this takes a long time for 6 workers, but would be an age for 100. 

This takes user time but also since the billing for the first VM will start immediately but your cluster isn't ready till the last VM is available it also wastes money.

**What you expected to happen**:

All VMs to create in parallel. A cluster of 1, 6 or 100 workers should take approximately the same time to start.

**Minimal Complete Verifiable Example**:

```python
from dask_cloudprovider.azure import AzureVMCluster
cluster = AzureVMCluster(resource_group="PangeoUSEast", vnet="dask-eus2", security_group="dask", n_workers=6)
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2.30.0
- Python version: 3.8
- Operating System: AML VM - Ubuntu "16.04.7 LTS (Xenial Xerus)"
- Install method (conda, pip, source): pip

**Comment by jacobtomlinson** [comment]
Thanks @tam203, good catch!

Sadly we have to wait for the scheduler to start as it needs to be up in order for the workers to connect to it. Although we have been discussing colocating workers with the scheduler on larger VM sizes to get things even faster. But having the workers start sequentially is a problem.

I think two things are happening here with the main problem being this line.

https://github.com/dask/dask-cloudprovider/blob/fef42793263718ce867888843c024ef384b3e957/dask_cloudprovider/azure/azurevm.py#L158

- Dask Cluster objects use asyncio and create the workers in parallel. However the Azure library does not support asyncio so control is not handed back to the event loop while we wait. 
- We are waiting for the VM to be created before finishing the instantiation of the `Worker` object. This seems to take a reasonably long time on Azure, so we are noticing this in a way we haven't on other clouds. But I think maybe Azure is being smart here and waiting for the machine to actually be running, other clouds just boot and move on.

Therefore I think there are two fixes that would be helpful here.

- We should run these calls in [async threadpool executors](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor). This would enable concurrency despite the underlying libraries not supporting asyncio.
- We should potentially consider not waiting for the VM to start. We have to wait for things like the IP and NIC to be provisioned as they are dependencies for the VM creation. But we might not need to wait for the VM to come up. My only reservation is perhaps the `wait()` call raises some errors that the `begin_create_or_update` does not.

**Comment by lostmygithubaccount** [comment]
@jacobtomlinson will you be able to fix this?

**Comment by jacobtomlinson** [comment]
Yeah it's on my backlog. Hoping to get to it this week.
