### ISSUE TITLE
AzureVMCluster class setting up a Jupyter lab at the workspace datastore like the AzureMLCluster class did

### ISSUE THREAD

**Issue by manuelreyesgomez** [dask/dask-cloudprovider#192]
In addition to setting up the cluster the AzureMLCluster class also sets up a Jupyter Lab on the scheduler that the user could access in it local machine through a link returned as a property of the resulting object. The link was "rooted" at the default data store for the workspace provided. I am aware that a key difference between the two classes is that the  AzureMLCluster uses Compute Clusters which are referred by workspace and the AzureVMCluster class uses VMs that are referred by ResourceGroup and then there is no reference to a specific workspace. Wondering if there would be any way to provide externally a workspace reference to have the JupyterLab rooted at its default workspace

**Comment by jacobtomlinson** [comment]
@lostmygithubaccount do you have any thoughts here on how we could replicate the Jupyter functionality of `AzureMLCluster` in `AzureVMCluster`?

**Comment by lostmygithubaccount** [comment]
@jacobtomlinson I would imagine the best solution is to start a Jupyter server in the Docker container running on the scheduler?

**Comment by manuelreyesgomez** [comment]
@jacobtomlinson @lostmygithubaccount  Thanks for the help. I was looking at some code we had used to set up a Jupyter notebook on a single (no dask cluster) Compute Cluster on the default data store for a given workspace, similar to what the AzureMLCluster class does for that. The code uses subprocess.Popen to run the following command on the scheduler:

    cmd = (
        f" jupyter lab --ip 0.0.0.0 --port {args.jupyter_port}"
        f" --NotebookApp.token={token}"
    )
    cmd += f" --notebook-dir={mount_point}"
    cmd += f" --allow-root --no-browser"

Where mount_point is defined as:

    from azureml.core import Run
    run = Run.get_context()

    workspace_name = run.experiment.workspace.name.lower()
    run_id = run.get_details()["runId"]

    mount_point = f"/mnt/batch/tasks/shared/LS_root/jobs/{workspace_name}/azureml/{run_id.lower()}/mounts/"

Since the AzureVMClass is not using the AzureMLSDK there is not such a thing as a Run object available

So we would need to pass to a hypothetical Create_Jupyter_Lab() function the mount_point variable as a parameter

How could we generate such mount point in the scheduler (and the workers too for that matter) externally before running the  Create_Jupyter_Lab(). 

From the users credentials one could get the workspace information

Thanks

**Comment by manuelreyesgomez** [comment]
In the above, I am assuming the mount point is generated by the AzureML SDK before running the script that sets up the Jupyter Lab

**Comment by manuelreyesgomez** [comment]
Found an example here: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-train-with-datasets#mount-vs-download

How to mount a dataset, wondering if there is something similar with a data store. I naively tried but a datastore object does not have function mount

**Comment by jacobtomlinson** [comment]
Running Jupyter Lab on a Dask scheduler is covered in [this blog post](https://blog.dask.org/2019/09/13/jupyter-on-dask).

Accessing datastores outside of Azure ML is typically done with [adlfs](https://github.com/dask/adlfs). I'm wondering if things could be changed to work with this.

**Comment by manuelreyesgomez** [comment]
@jacobtomlinson @lostmygithubaccount 

In addition to setting it up a Jupyter Lab, the AzureMLCluster class also set up a port forwarding mechanism between the Compute Cluster working as the scheduler and the local machine that ran the code to generate the Dask Cluster. 

With this respect I have two questions

1) While specifying the configuration for the compute target, the user could specify two arguments that I think are important to enable the port forwarding: admin_user_ssh_key, remote_login_port_public_access. Wondering if there is a way to specify and set those parameters on a VM

2) The command that does the port forwarding set up requires the following value: cluster.list_nodes()[0]['port'], where cluster was generated with command cluster = ComputeTarget.create(ws, ct_name, config), which is the value for port seen on this dashboard:

![node](https://user-images.githubusercontent.com/39012886/100954637-cef27880-34c9-11eb-962d-489513cfd6ee.png)

Any insights/help on how to deal with these two issues would be great appreciated

**Comment by lostmygithubaccount** [comment]
you should be able to get all the SSH info you need, and I believe edit passwords/keys, from the Azure portal by navigating to the resource group and specific VM

**Comment by manuelreyesgomez** [comment]
Yeah but I need to be able to do it programmatically as before

**Comment by manuelreyesgomez** [comment]
Figured a work around
