### ISSUE TITLE
AzureVMCluster: scheduler takes entire VM

### ISSUE THREAD

**Issue by lostmygithubaccount** [dask/dask-cloudprovider#193]
**What happened**:

Creating a Dask cluster of GPUs as in the example results in one VM being created for the scheduler, without also being available as a worker which is wasteful.

**What you expected to happen**:

I think this is a known issue, and I'm not sure what the solution is - I believe in AzureMLCluster we'd simply start the scheduler and worker on the same node.

**Minimal Complete Verifiable Example**:

```python
location="eastus"
resource_group = "dask-cloudprovider"
vnet = "dask-vnet"
security_group = "dask-nsg"

vm_size = "Standard_NC12s_v3"
docker_image="rapidsai/rapidsai:cuda11.0-runtime-ubuntu18.04-py3.8"
worker_class="dask_cuda.CUDAWorker"

from distributed import Client
from dask_cloudprovider.azure import AzureVMCluster

cluster = AzureVMCluster(location=location, resource_group=resource_group, vnet=vnet, security_group=security_group, vm_size=vm_size, docker_image=docker_image, worker_class=worker_class)
c = Client(cluster)
c
```

**Anything else we need to know?**:

Should this be fixed in the generic VMCluster? In each cloud provider? 

**Environment**:

- Dask version: 2.30.0
- Python version: 3.8
- Operating System: macOS
- Install method (conda, pip, source): pip

**Comment by jacobtomlinson** [comment]
This is slightly tricky because there is a chance that the scheduler can deserialise things. It shouldn't but it can happen.

Therefore the scheduler requires a GPU if the workers have GPUs.

Perhaps we should look at specifying a different VM size for the scheduler, so the scheduler could be put on a `Standard_NC6s_v3`.

cc @quasiben who may know more about what the scheduler requires

**Comment by jacobtomlinson** [comment]
> I believe in AzureMLCluster we'd simply start the scheduler and worker on the same node.

This is also something that we could think about doing. But it does mean that worker will have slightly less resource available than other workers, which could lead to some edge case bugs.

**Comment by quasiben** [comment]
@jacobtomlinson, is correct.  There are probably remaining issues with the scheduler deserializing a bit of GPU data -- we haven't had time to properly test this.   At the very least, the recommendation should be running the scheduler with a GPU.  For CPU only deployments, the scheduler may not need the same amount of resources as the worker and having a heterogenous deployment would be very nice!

**Comment by jacobtomlinson** [comment]
Thanks @quasiben!

I think it would make sense in the short term to enable selecting smaller instance types for the scheduler. In this example it would be nice to choose a `Standard_NC6s_v3` with 1 GPU for the scheduler and `Standard_NC24s_v3` for the workers with 4 GPUs. The scheduler does not need four.

**Comment by lostmygithubaccount** [comment]
that seems reasonable for now, and might also be applicable to some of the CPU skus e.g. `Standard_D64s_v2` where I may not want a 64 cpu scheduler.

@jacobtomlinson what would be the correct way to implement this?

**Comment by jacobtomlinson** [comment]
I think it will need implementing differently for each cluster as we use different kwargs in order to be consistent with the cloud providers vocabulary.

I've raised #195 to implement this for Azure. We need to do this for AWS and GCP too.
