### ISSUE TITLE
Allow for GCP external IPs when public_ingress is False

### ISSUE THREAD

**Issue by eric-czech** [dask/dask-cloudprovider#215]
I think this change may have been a bit extreme, or that it would be useful if it was decoupled from the `public_ingress` option: https://github.com/dask/dask-cloudprovider/pull/164/files#diff-113dfeb18ca47da584fa2c3b3d458504cc6260f0fda1055b0004f10b2b736d62R157

The use case I have is that I'm fine with VMs having external IPs, but I don't want to open up ports for anything other than ssh.  The `public_ingress=False` setting forces dask to communicate on non-ssh ports using internal ips, which is great, but the lack of an external IP means I have no way to reach hosts to debug anything.  

Personally, I think the easiest option is to change it back so the external IP is always provisioned.  Do the other VMCluster implementations ever do this conditionally?

**Comment by jacobtomlinson** [comment]
Thanks for raising this @eric-czech.

This is an interesting point. Generally we make the provisioning of a public IP a boolean option. I actually think we are have made a bit of a mistake in general by having the workers connect on the public IP. I think workers should always connect privately and then the public toggle just exposes the scheduler, or not.

Out of curiosity could you use the [`gcloud` CLI](https://cloud.google.com/sdk/gcloud/reference/compute/ssh) to gain command line access to the machines without exposing port 22 at all?

**Comment by jacobtomlinson** [comment]
Hrm looks like I may have already thought about this and then forgotten when implementing these new cluster managers.

dask/distributed#2963

**Comment by eric-czech** [comment]
> Out of curiosity could you use the gcloud CLI to gain command line access to the machines without exposing port 22 at all?

I tried with that code change to ssh to the scheduler from another GCP VM and it didn't work.  I say "that code change" instead of without an external IP because I don't know enough to say if there are other implications of having no "compute#accessConfig" set.  Perhaps there are other options?

> Hrm looks like I may have already thought about this and then forgotten when implementing these new cluster managers.

Heh, +1 to external management and internal communication.  

A crude way I see the possibilities after reading that is:

1. Everything is public
2. Cluster hosts have management ports open to the world and no open application ports
3. Cluster hosts are not addressable outside of a VPC though certain proxy hosts are

The third option is obviously best but a bane for new users no doubt.  I suppose I'm advocating for the second option in this issue, but I can understand if it's between stools.

**Comment by quasiben** [comment]
In GCP dask workers I believe always connect with internal addresses:

https://github.com/dask/dask-cloudprovider/blob/ad4eb0eb7444c35ce3beaedc4c510abe6706f03e/dask_cloudprovider/gcp/instances.py#L310-L317


I thought that what is currently listed under `public_ingress` controls whether the an external IP is attached:

```python
                {
                    "kind": "compute#accessConfig",
                    "name": "External NAT",
                    "type": "ONE_TO_ONE_NAT",
                    "networkTier": "PREMIUM",
                }
```

We can additionally use other network interfaces which control what ports are open (previously built in GCP by the user).  I think (still learning GCP network infrastructure), the GCP user can create a VPC network, then create some firewall rules for that network (both ingress and egress).  GCPCluster should then optionally take in that info and build something like following:

```python
 {
      "kind": "compute#networkInterface",
      "subnetwork": "projects/PROJECT-ID/regions/ZONE/subnetworks/SUBNETWORKNAME",
      "accessConfigs": [
        {
          "kind": "compute#accessConfig",
          "name": "External NAT",
          "type": "ONE_TO_ONE_NAT",
          "networkTier": "PREMIUM"
        }
      ],
      "aliasIpRanges": []
    },
```

We could also check for `external_address` here in cloudprovider:
https://github.com/dask/dask-cloudprovider/blob/ad4eb0eb7444c35ce3beaedc4c510abe6706f03e/dask_cloudprovider/generic/vmcluster.py#L41-L43

**Comment by eric-czech** [comment]
> In GCP dask workers I believe always connect with internal addresses

Ah I see, thanks Ben.  I was experimenting with this a little more and found that with `public_ingress=False` on current master, clusters don't launch because the machines can't install software from public sources.  I.e. the cloud-init logs are filled with things like this:

<details><summary>/var/log/cloud-init-output.log on scheduler</summary>

```
/var/lib/cloud/instance/scripts/runcmd: 3: /var/lib/cloud/instance/scripts/runcmd: add-apt-repository: not found
Err:1 http://us-east1.gce.archive.ubuntu.com/ubuntu bionic InRelease
  Could not connect to us-east1.gce.archive.ubuntu.com:80 (35.196.65.164), connection timed out Could not connect to us-east1.gce.archive.ubuntu.com:80 (35.196.128.168), connection timed out Could not connect to us-east1.gce.archive.ubuntu.com:80 (35.196.129.83), connection timed out
Err:2 http://archive.canonical.com/ubuntu bionic InRelease
  Could not connect to archive.canonical.com:80 (91.189.92.191), connection timed out Could not connect to archive.canonical.com:80 (91.189.91.15), connection timed out Could not connect to archive.canonical.com:80 (91.189.92.150), connection timed out
Err:3 http://us-east1.gce.archive.ubuntu.com/ubuntu bionic-updates InRelease
  Unable to connect to us-east1.gce.archive.ubuntu.com:http:
Err:4 http://us-east1.gce.archive.ubuntu.com/ubuntu bionic-backports InRelease
  Unable to connect to us-east1.gce.archive.ubuntu.com:http:
Err:5 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Could not connect to security.ubuntu.com:80 (91.189.91.38), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.142), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.39), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.152), connection timed out
Reading package lists...
W: Failed to fetch http://us-east1.gce.archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Could not connect to us-east1.gce.archive.ubuntu.com:80 (35.196.65.164), connection timed out Could not connect to us-east1.gce.archive.ubuntu.com:80 (35.196.128.168), connection timed out Could not connect to us-east1.gce.archive.ubuntu.com:80 (35.196.129.83), connection timed out
W: Failed to fetch http://us-east1.gce.archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Unable to connect to us-east1.gce.archive.ubuntu.com:http:
W: Failed to fetch http://us-east1.gce.archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  Unable to connect to us-east1.gce.archive.ubuntu.com:http:
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Could not connect to security.ubuntu.com:80 (91.189.91.38), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.142), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.39), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.152), connection timed out
W: Failed to fetch http://archive.canonical.com/ubuntu/dists/bionic/InRelease  Could not connect to archive.canonical.com:80 (91.189.92.191), connection timed out Could not connect to archive.canonical.com:80 (91.189.91.15), connection timed out Could not connect to archive.canonical.com:80 (91.189.92.150), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package docker-ce
E: Unable to locate package docker-ce-cli
E: Unable to locate package containerd.io
E: Couldn't find any package by glob 'containerd.io'
E: Couldn't find any package by regex 'containerd.io'
Failed to start docker.service: Unit docker.service not found.
Failed to enable unit: Unit file docker.service does not exist.
/var/lib/cloud/instance/scripts/runcmd: 8: /var/lib/cloud/instance/scripts/runcmd: docker: not found
2020-12-12 10:38:41,296 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2020-12-12 10:38:41,297 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
ci-info: no authorized SSH keys fingerprints found for user ubuntu.
Cloud-init v. 20.3-2-g371b392c-0ubuntu1~18.04.1 finished at Sat, 12 Dec 2020 10:38:41 +0000. Datasource DataSourceGCE.  Up 429.01 seconds
```
</details>

I did figure out how to connect to the nodes without an external address though.  I didn't realize that `gcloud beta compute ssh` was always trying to use an external ip so it was as simple as adding `gcloud beta compute ssh --internal-ip ...` when the client is also in GCP.

I still feel like there is a case to be made for the scheduler to have an external IP while the workers do not.  Would you guys agree there or do you think based on implementations for other cloud providers (or maybe Coiled? cc: @mrocklin) that the only two options should be everything has a public IP or nothing does?  

In any case, I'm not sure what to do about installing software from the internet without a public IP.  Has this come up before?

**Comment by jacobtomlinson** [comment]
> I still feel like there is a case to be made for the scheduler to have an external IP while the workers do not.

I think this should be the general case. There isn't really any reason why the workers should get a public IP. They do not in other cluster managers. So I'm +1 to making that change here.

> I'm not sure what to do about installing software from the internet without a public IP

I am most familiar with AWS, and I know over there that if you do not assign a public IP you have the same problem, no routing to the internet. To work around it you need to have a NAT gateway in your VPC to handle this routing. [It's a pretty standard model in AWS](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html), but a little cumbersome for beginners. A quick search shows [Google have something with a similar name](https://cloud.google.com/nat/docs/overview), so perhaps the same approach needs to be taken here.

**Comment by eric-czech** [comment]
> To work around it you need to have a NAT gateway in your VPC to handle this routing.

Nice, thanks!  I'll try to figure that out if I can't get more public IPs.
