### ISSUE TITLE
Issue with AzureVMCluster workers stopping right away

### ISSUE THREAD

**Issue by manuelreyesgomez** [dask/dask-cloudprovider#216]
Setting up a cluster as recommended, but as soon as it completes, it reports zero workers (there should be 4), it was working fine before

![AzureVMRun](https://user-images.githubusercontent.com/39012886/101851802-1eabf200-3b11-11eb-99d4-21c8fe29e94f.png)

The workers appear as Stopped on the Azure Portal

![AzureVMAzurePortalIssue](https://user-images.githubusercontent.com/39012886/101851953-6a5e9b80-3b11-11eb-9037-9125a35b1a2e.png)

Please be concise with code posted. See guidelines below on how to provide a good bug report:

- Craft Minimal Bug Reports http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports
- Minimal Complete Verifiable Examples https://stackoverflow.com/help/mcve

Bug reports that follow these guidelines are easier to diagnose, and so are often handled much more quickly.
-->

**What happened**:

**What you expected to happen**:

**Minimal Complete Verifiable Example**:

```python
# Put your MCVE code here
```

**Anything else we need to know?**:

**Environment**:

- Dask version:
- Python version:3.7
- Operating System: Windows
- Install method (conda, pip, source): pip

**Comment by quasiben** [comment]
Hmm, did you define a `docker_image`  with RAPIDS ?  If not, the default will be `daskdev/dask:latest` and will not be able to launch dask-cuda workers

**Comment by manuelreyesgomez** [comment]
That might be the problem. I actually forgot to specify a docker_image all together

**Comment by manuelreyesgomez** [comment]
Yeah, it is now working as expected, my bad, thanks for the prompt response
