### ISSUE TITLE
For AzureVMCluster, to have the configurable option to give the container extra privileges to mount data

### ISSUE THREAD

**Issue by manuelreyesgomez** [dask/dask-cloudprovider#223]
I would like to be able to mount a workspace datastore into the scheduler and the workers to do so I need the containers on them to be run with extra privileges to be able to use FUSE to do the mounting

Using: 

docker run --privileged 

or 

docker run --cap-add SYS_ADMIN --device /dev/fuse

I understand it is not desirable to have this option as the default so it would be able if it is a configurable option

Thanks

**Comment by manuelreyesgomez** [comment]
Hello, any update on this request, thanks

**Comment by jacobtomlinson** [comment]
I've proposed adding an extra configuration option to enable this in #236. Would you mind checking it out and giving feedback?
