### ISSUE TITLE
When the deploy client is within GCE use internal IP address

### ISSUE THREAD

**Issue by ravwojdyla** [dask/dask-cloudprovider#229]
This is related to #161 and #215.
The use case:
 * the deployment client is within GCE
 * we want to have public IPs (to easily download software etc, without setting up NAT gateway)
 * we don't want to configure firewall rules to allow 8787 etc traffic to external IP

To allow for this, in the client deployment code we can check if we are running in GCE and if we do, use internal IP as the address, here:
https://github.com/dask/dask-cloudprovider/blob/02b50e2efe4a98f6442e24aaedea237577cad0eb/dask_cloudprovider/gcp/instances.py#L295-L301

additionally in `wait_for_scheduler` we could add ip/port to the message to make it clear which IP the client is waited on, here:
https://github.com/dask/dask-cloudprovider/blob/02b50e2efe4a98f6442e24aaedea237577cad0eb/dask_cloudprovider/generic/vmcluster.py#L42-L45

This would streamline the deployment of GCP cluster as it removes the extra steps (firewall rules/NAT gateway). Alternatively we could also consider waiting on scheduler on both IPs at the same time, but I would lean towards simpler solution first.
FYI @eric-czech, wdyt?

**Comment by eric-czech** [comment]
Sounds great!

>  we can check if we are running in GCE

Is there a standard way to do that?

> This would streamline the deployment of GCP cluster as it removes the extra steps (firewall rules/NAT gateway)

How does it do that if the instances don't have external IPs?   Without this [line](https://github.com/dask/dask-cloudprovider/pull/164/files#diff-113dfeb18ca47da584fa2c3b3d458504cc6260f0fda1055b0004f10b2b736d62R157), none of the instances I launched could reach the internet.

**Comment by ravwojdyla** [comment]
@eric-czech 

>> we can check if we are running in GCE

> Is there a standard way to do that?

I mostly check if `metadata.google.internal` is available.

> How does it do that if the instances don't have external IPs? Without this line, none of the instances I launched could reach the internet.

The assumption is that we we want to have public IPs for this use case.
