### ISSUE TITLE
Add plugin for preemptible instances.

### ISSUE THREAD

**Issue by Timost** [dask/dask-cloudprovider#239]
Hi !

Following some discussions in dask/distributed#4421. I've implemented a worker plugin that calls azure metadata service to check for node eviction in AKS and try to shut down workers as cleanly as possible. @jacobtomlinson suggested I contribute it to this repo in https://github.com/dask/distributed/issues/4421#issuecomment-760129128 somewhere in `dask_cloudprovider.azure.utils`.

Before opening an MR I would like some pointers on where to put the actual code and the associated documentation.
Thank you.

**Comment by jacobtomlinson** [comment]
Thanks for raising this.

I would suggest your Azure code goes in a file called `dask_cloudprovider/azure/utils.py` with a top-level import in `dask_cloudprovider/azure/__init__.py` to enable `from dask_cloudprovider.azure import PreemptiveWorkerPlugin` or whatever you call the class.

Docs should be in the docstring of the class and then exposed in `doc/source/azure.rst` via an `autoclass::` directive.
