### ISSUE TITLE
Move default branch from "master" -> "main"

### ISSUE THREAD

**Issue by jsignell** [dask/dask-cloudprovider#244]
@jrbourbeau and I are in the process of moving the default branch for this repo from master to main. 

 - [x] Changed in GitHub
 - [x] Merged PR to change branch name in code. #245

What you need to do locally:

```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by jrbourbeau** [comment]
@jacobtomlinson we haven't updated the name of the default branch yet. Just wanted to check first to make sure there aren't any blockers on making the `master` -> `main` change here

**Comment by jacobtomlinson** [comment]
I think things should be all good to switch here. Thanks for taking this on.

**Comment by jacobtomlinson** [comment]
I'm about to release here, but that shouldn't be a problem as the release CI is set up to release all tags, regardless of branch.

**Comment by jrbourbeau** [comment]
Awesome thanks!

**Comment by jacobtomlinson** [comment]
The release is complete, just FYI.

**Comment by jacobtomlinson** [comment]
Small note you need to rename the branch in your fork before those local commands will work.

**Comment by jacobtomlinson** [comment]
Another note that I just spotted. Read The Docs was still building `latest` from the `master` branch and builds were failing. It was configured to build from the default branch, but I think it had cached the value `master` somewhere. I manually pointed this to `main` in the RtD control panel and things seem ok again now.

cc @jrbourbeau @jsignell as it may be worth checking other projects too.

**Comment by jrbourbeau** [comment]
Will do, thanks for the heads up @jacobtomlinson

**Comment by jacobtomlinson** [comment]
The same issue also came up on `dask-kubernetes`.

**Comment by jsignell** [comment]
I imagine this will come up in all the projects. Would it help for me to go through all the repos and open a ticket about this? Or is it sufficient for someone to just get in and change them all?

**Comment by jacobtomlinson** [comment]
It might be worth opening issues as permissions in RtD are a little more ad-hoc than GitHub. There are no orgs so folks have to be added to each project manually.

Perhaps @jrbourbeau or @mrocklin have been added to enough projects to be able to go through and fix everything? But I do not.
