### ISSUE TITLE
gcp config edit mechanism

### ISSUE THREAD

**Issue by verasativa** [dask/dask-cloudprovider#252]
Hi, I was trying to create a cluster with E2 machines on gcp, but default config at gcp/instances.py:150 set "onHostMaintenance" to "TERMINATE" which is not allowed on that kind of machines. I juste edited the file to MIGRATE and worked. But maybe there is proper way to set it, would you point me to it if it does exist. Else, how should be address?

**Comment by JALVARADORUIZ** [comment]
interesting solution, but it would be good to know if there is another way to do it ....

**Comment by quasiben** [comment]
@verasativa do you know if this kind of information is written down in any google API documentation ?

**Comment by PauForestal** [comment]
I have the same issue, and it's too complicated to solve... is there another solution? I don't understand how to do it!

**Comment by verasativa** [comment]
> @verasativa do you know if this kind of information is written down in any google API documentation ?

not sure, I notice that rule while trying to deploy (with API response). To be honest gcp is kind of inconsistent and under-documented (but cheap and available).

**Comment by quasiben** [comment]
@verasativa do you have thoughts on PR #253 ?

**Comment by verasativa** [comment]
Looks pretty good to me. 
Also:
Have you considerate changing default machine type to current gcp console default machine (```e2-medium```) ?

**Comment by quasiben** [comment]
I have not but perhaps there is reason to.  At the moment we were optimizing for machine types which had both CPU and GPU capabilities.  I don't think the E series can connect to GPUs.  Is that correct ?

**Comment by verasativa** [comment]
I understand, you are right, E series can't connect to GPUs.

**Comment by PauForestal** [comment]
Sounds great, but I have a question. Do you use GPU only for deep learning? Do you have some posts or blogs or some references where I can understand better why GPU is useful with Dask?

**Comment by quasiben** [comment]
Yes, we use GPUs for more than deep learning.  Some of us are employed by NVIDIA to help build [RAPIDS](https://rapids.ai) and generally support GPUs for the PyData ecosystem.  I'd recommend starting with the following

- https://blog.dask.org/2019/06/19/python-gpus-status-update
- https://rapids.ai/
- https://medium.com/rapids-ai/nvtabular-all-in-on-dask-6241b4e9ca19

**Comment by PauForestal** [comment]
Wow, thanks a lot! I'm gonna read it right now
