### ISSUE TITLE
Option to not specify launchType in ECS task

### ISSUE THREAD

**Issue by kinghuang** [dask/dask-cloudprovider#261]
When using ECSCluster, the generated ECS task includes `"launchType": "FARGATE" if self.fargate else "EC2"` ([ec2.py#L247](https://github.com/dask/dask-cloudprovider/blob/adca69c94348181daa4f56cac8ab9597081483bd/dask_cloudprovider/aws/ecs.py#L247)). This makes it impossible to use the default capacity provider for an ECS cluster, by not specifying `capacityProviderStrategy` or `launchType`.

From [RunTask](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html) API docs:

> If no `capacityProviderStrategy` or `launchType` is specified, the defaultCapacityProviderStrategy for the cluster is used.

The current implementation also makes it impossible to specify a `capacityProviderStrategy` via `task_kwargs`, because `capacityProviderStrategy` and `launchType` cannot be specified together.

> If a `capacityProviderStrategy` is specified, the `launchType` parameter must be omitted.

I would like a way to *not* specify `launchType` with ECSCluster, so that I can either use the cluster's default capacity provider or specify a `capacityProviderStrategy`.

**Comment by jacobtomlinson** [comment]
Thanks for raising this @kinghuang. That sounds like a reasonable request.

Do you have any interest in raising a Pull Request to resolve this?

**Comment by kinghuang** [comment]
Interest, yes. But, lacking in available time. :)

I'll circle back to this later in the month, if no one else picks it up!

**Comment by kinghuang** [comment]
I'll pick this up on Wednesday.
