### ISSUE TITLE
ssd option for GCPCluster

### ISSUE THREAD

**Issue by ahah-figure** [dask/dask-cloudprovider#272]
It would be nice to be able to specify ssds for the nodes when you instantiate a GCPCluster. For example, when you create a cluster in gcloud, you can pass parameters like

    --master-boot-disk-type pd-ssd
    --worker-boot-disk-type pd-ssd

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @ahah-figure! I've transferred this issue over to `dask-cloudprovider` as that's the relevant project for `GCPCluster`

**Comment by jacobtomlinson** [comment]
It looks like we are setting this here

https://github.com/dask/dask-cloudprovider/blob/bc949ee2d8cfa6161c4e424973356ac007fd599e/dask_cloudprovider/gcp/instances.py#L113

It would be great to make this configurable.
