### ISSUE TITLE
FargateCluster does not accept region kwarg

### ISSUE THREAD

**Issue by brkeating** [dask/dask-cloudprovider#280]
**Minimal Complete Verifiable Example**:

```
from dask_cloudprovider.aws import FargateCluster
cluster = FargateCluster(region='us-west-2')
```

**What happened**:

`TypeError: __init__() got an unexpected keyword argument 'region'`

**What you expected to happen**:

Creation of a valid `FargateCluster` object.

**Environment**:

- Dask version: 2021.3.1
- Python version: 3.9.2
- Operating System: OSX 10.14
- Install method (conda, pip, source): pip 21.0.1 inside a fresh conda env

**Comment by brkeating** [comment]
The argument is `region_name`; `region` is for an `EC2Cluster`. It would be nice if these were consistently named

**Comment by jacobtomlinson** [comment]
Agreed. Do you have any interest in raising a PR to align them?
