### ISSUE TITLE
AWS Fargate: public scheduler /w private workers?

### ISSUE THREAD

**Issue by valpesendorfer** [dask/dask-cloudprovider#288]
I've recently ran into some issues with the fact that by default both the scheduler and workers get public IPs assigned within the cluster.

On the one side this seems to incur some unnecessary costs as

> Any data transfer between EC2 instances or containers or Elastic Network Interfaces in the same Availability Zone and in the same VPC, whether using Public or Elastic IPv4 addresses, comes with an egress charge of $0.01 per GB and an ingress charge of $0.01 per GB

and in [another case](https://github.com/dask/dask-cloudprovider/issues/56#issuecomment-852080328) it had me running out of available IP addresses causing the workers to fail on startup.

What's the best way to handle this? I know the workers don't need a public IP, pulling the image can be facilitated using a NAT or VPC endpoint.  The straight forward solution would be to set `fargate_use_private_ip` to `True` in case of Fargate, but then the scheduler also only gets a private IP which prohibits the dashboard access. 

Is there any way to keep the public IP for the scheduler while keeping the workers fully private (as they don't need to be reachable from outside)? Or is there another easy way to keep the dashboard access with private workers? I recon it could be tunneled, but is that the easiest way? I was hoping the lab-extension can display the dashboard if it's in the same VPC, [but I couldn't make it work yet](https://github.com/dask/dask-labextension/issues/194).

I was looking through the issues to find some answers, but haven't really found anything conclusive. I've seen that there are/were similar discussions [for GCP](https://github.com/dask/dask-cloudprovider/issues/215), [EC2 (kinda)](https://github.com/dask/dask-cloudprovider/issues/284), [Fargate already](https://github.com/dask/dask-cloudprovider/issues/287) 
and [Feature for the SpecCluster](https://github.com/dask/distributed/issues/2962) that [got implemented in distributed](https://github.com/dask/distributed/pull/2963), but not sure if that is applicable here.

Thanks!

**Comment by jacobtomlinson** [comment]
My suggestion would be to use private networking for the Dask cluster and then make use of the [Jupyter server proxy extension](https://jupyter-server-proxy.readthedocs.io/en/latest/arbitrary-ports-hosts.html) to access the Jupyter dashboard via the public IP on the EC2 instance you're running Jupyter on.

**Comment by valpesendorfer** [comment]
Ok, thanks. Seems like the easiest solution. I'll go ahead and close the issue.
