### ISSUE TITLE
FargateCluster IAM permission list incomplete

### ISSUE THREAD

**Issue by aulemahal** [dask/dask-cloudprovider#295]
**What happened**:
After adding all IAM permissions listed in the doc to my AWS account, creating a FargateCluster still fails with `ClientError (AccessDeniedException)`. After adding the missing permissions, it failed again on another. I hope there are no other, the back and forth with those managing my account (in a different timezone) is a bit time-consuming.

**My code:**
```python
from dask_cloudprovider.aws import FargateCluster
from dask.distributed import Client

cluster = FargateCluster(n_workers=8, worker_mem=8*1024, image="aulemahal/xclim-stack")
client = Client(cluster)
```

**What you expected to happen**:
I expected the list of IAM permissions in the doc to be complete.

**Anything else we need to know?**:
Up to now, the missing permissions are: 

- logs:CreateLogGroup
- logs:PutRetentionPolicy

**Environment**:

- Dask version: Cloudprovider : 2021.03.1, Dask : 2021.02.1, aiobotocore : 1.1.2
- Python version: 3.7.10
- Operating System: linux
- Install method (conda, pip, source): pip (with --user)

**Comment by jacobtomlinson** [comment]
Thanks for raising this and identifying the missing permissions!
