### ISSUE TITLE
Uncomment the config file and use those defaults

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-cloudprovider#3]
We should be able to safely uncomment the config file in cloud.yaml .  Dask will both use these values as baseline defaults, which should stop us from having to double-specify them in sourcecode like here:

```python
        self._scheduler_cpu = (
            self.config.get("scheduler_cpu", 1024)  # <-- default now in two places
            if self._scheduler_cpu is None
            else self._scheduler_cpu
        )
```

and it will automatically comment out the user's version as it includes it in `~/.config/dask/cloud.yaml` by default.

**Comment by jacobtomlinson** [comment]
What happens if a user edits their `~/.config/dask/cloud.yaml` and removes a config item?

**Comment by mrocklin** [comment]
You load a copy of the baseline configuration when we import the library and call `dask.config.update_defaults` here

https://github.com/jacobtomlinson/dask-cloud/blob/36502620ab7f93bb1279192b973881eba50ce088/dask_cloud/config.py#L15

This reads the uncommented [cloud.yaml](https://github.com/jacobtomlinson/dask-cloud/blob/master/dask_cloud/cloud.yaml) file that we distribute with library.

The file that we copy into the `~/.config/dask` directory will also be this file, but after we automatically comment everything out.

**Comment by KyleJN27** [comment]
How does precedence work with a file in the directory that is specified in `DASK_CONFIG`. Will that file override the defaults set in `~/.config/dask`?

**Comment by mrocklin** [comment]
Yes.  https://docs.dask.org/en/latest/configuration.html

Dask searches for *all* YAML files within each of these directories and
merges them together, preferring configuration files closer to the user
over system configuration files (preference follows the order in the list
above). Additionally, users can specify a path with the DASK_CONFIGenvironment
variable, which takes precedence at the top of the list above.
