### ISSUE TITLE
Allow specifying different docker_image for scheduler

### ISSUE THREAD

**Issue by rossrochford** [dask/dask-cloudprovider#304]
I want to be able to run an AzureVMCluster with GPU workers but have no GPU on the scheduler. I can specify the scheduler_vm_size but this seems to cause issues with the CUDA docker image I'm using. I suggest adding an optional "scheduler_docker_image" argument.

**Comment by jacobtomlinson** [comment]
The `scheduler_vm_size` kwarg is intended to allow you to select a VM with one GPU for the scheduler if you have chosen a VM size with multiple GPUs for the workers.

It is not advisable to run the scheduler with no GPU at all as there are edge case scenarios where GPU code can be deserialized on the scheduler.

**Comment by rossrochford** [comment]
Thank you for the response. Ok, that is a shame given how expensive GPU instances are. I guess I can use Terraform instance and put the scheduler on a node shared with workers.

**Comment by jacobtomlinson** [comment]
This package is intended for deploying ephemeral Dask clusters with many workers. So if you have 8, 16, 24 or even more GPUs then the cost of the scheduler is only a small percentage.

If you're looking to run just a single GPU workload this may not be the tool for you, you might not even need Dask. You may want to look into starting a GPU node yourself and then using [dask-cuda](https://github.com/rapidsai/dask-cuda) directly.

I'm going to close this issue out but if you want any more help with using Dask then check out our [Slack channel](https://join.slack.com/t/dask/shared_invite/zt-mfmh7quc-nIrXL6ocgiUH2haLYA914g).

**Comment by rossrochford** [comment]
Thank you, yes I'm going to launch the cluster myself so I have a little more control.
