### ISSUE TITLE
Can we improve reprs

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-cloudprovider#31]
Currently the `FargateCluster` and `ECSCluster` use the reprs inherited from distributed `Cluster` and `SpecCluster`.

![image](https://user-images.githubusercontent.com/1610850/63851258-cb4e7880-c98d-11e9-9dfa-59117b73695a.png)

Could these be improved to convey more useful information that is specific to Dask Cloudprovider?

**Comment by jacobtomlinson** [comment]
cc @mrocklin

**Comment by jacobtomlinson** [comment]
That would be useful. I was just thinking about whether there would be any cloud provider specific info that would be useful. The only one that jumps to mind would be Fargate cost info (#21).

I mainly raised this in a response to you asking "Does this not have a nice repr?" somewhere else.

I'm tempted to say that these reprs from the upstream `Cluster` classes are fine.

**Comment by mrocklin** [comment]
Ah, my comment before was mostly so that we could remove a print statement,
and rely on __repr__, which seems decent to me

**Comment by jacobtomlinson** [comment]
Ok great!
