### ISSUE TITLE
Azure - Token Resource Error

### ISSUE THREAD

**Issue by marcelned** [dask/dask-cloudprovider#315]
Running the example from the tutorial, ie

```python
from dask_cloudprovider.azure import AzureVMCluster
cluster = AzureVMCluster(resource_group="<resource group>",
                         vnet="<vnet>",
                         security_group="<security group>",
                         n_workers=1)
```

The following error keeps popping up:

![image](https://user-images.githubusercontent.com/82392567/137031235-1bd39361-62c0-4c2d-bd04-046ae55242b2.png)

Thanks for the help

**Comment by jacobtomlinson** [comment]
Thanks for raising this @marcelned. Could you share the full traceback?

Thanks!

**Comment by marcelned** [comment]
Here is the full environment:

'''yaml
name: dask_azure
channels:
  - conda-forge
dependencies:
  - appnope=0.1.2=py39h6e9494a_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - ca-certificates=2021.10.8=h033912b_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - ipython=7.28.0=py39h71a6800_0
  - jedi=0.18.0=py39h6e9494a_2
  - libcxx=12.0.1=habf9029_0
  - libffi=3.4.2=he49afe7_4
  - libzlib=1.2.11=h9173be1_1013
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h2e338ed_4
  - openssl=3.0.0=h0d85af4_1
  - parso=0.8.2=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py39hde42818_1002
  - pip=21.3=pyhd8ed1ab_0
  - prompt-toolkit=3.0.20=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pygments=2.10.0=pyhd8ed1ab_0
  - python=3.9.7=h38b4d05_3_cpython
  - python_abi=3.9=2_cp39
  - readline=8.1=h05e3726_0
  - setuptools=58.2.0=py39h6e9494a_0
  - sqlite=3.36.0=h23a322b_2
  - tk=8.6.11=h5dbffcc_1
  - traitlets=5.1.0=pyhd8ed1ab_0
  - tzdata=2021c=he74cb21_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.0=pyhd8ed1ab_1
  - xz=5.2.5=haf1e3a3_1
  - zlib=1.2.11=h9173be1_1013
  - pip:
    - adal==1.2.7
    - aiobotocore==1.4.2
    - aiohttp==3.7.4.post0
    - aioitertools==0.8.0
    - applicationinsights==0.11.10
    - argcomplete==1.12.3
    - async-timeout==3.0.1
    - attrs==21.2.0
    - azure-cli-core==2.29.0
    - azure-cli-telemetry==1.0.6
    - azure-common==1.1.27
    - azure-core==1.19.0
    - azure-mgmt-compute==23.1.0
    - azure-mgmt-core==1.2.2
    - azure-mgmt-network==19.1.0
    - bcrypt==3.2.0
    - botocore==1.20.106
    - cachetools==4.2.4
    - certifi==2021.10.8
    - cffi==1.14.6
    - chardet==4.0.0
    - click==8.0.3
    - cloudpickle==2.0.0
    - colorama==0.4.4
    - cryptography==35.0.0
    - dask==2021.9.1
    - dask-cloudprovider==2021.9.0
    - distributed==2021.9.1
    - fsspec==2021.10.0
    - future==0.18.2
    - google-api-core==2.1.0
    - google-api-python-client==2.26.1
    - google-auth==2.3.0
    - google-auth-httplib2==0.1.0
    - googleapis-common-protos==1.53.0
    - hcloud==1.16.0
    - heapdict==1.0.1
    - httplib2==0.20.1
    - humanfriendly==9.2
    - idna==2.10
    - isodate==0.6.0
    - jinja2==3.0.2
    - jmespath==0.10.0
    - jsonpickle==2.0.0
    - knack==0.8.2
    - locket==0.2.1
    - markupsafe==2.0.1
    - msal==1.15.0
    - msgpack==1.0.2
    - msrest==0.6.21
    - msrestazure==0.6.4
    - multidict==5.2.0
    - oauthlib==3.1.1
    - packaging==21.0
    - paramiko==2.8.0
    - partd==1.2.0
    - pkginfo==1.7.1
    - portalocker==1.7.1
    - protobuf==3.18.1
    - psutil==5.8.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pyjwt==2.2.0
    - pynacl==1.4.0
    - pyopenssl==21.0.0
    - pyparsing==2.4.7
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - python-digitalocean==1.17.0
    - pyyaml==5.4.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - six==1.16.0
    - sortedcontainers==2.4.0
    - tabulate==0.8.9
    - tblib==1.7.0
    - toolz==0.11.1
    - tornado==6.1
    - typing-extensions==3.10.0.2
    - uritemplate==4.1.1
    - urllib3==1.26.7
    - wrapt==1.13.2
    - yarl==1.7.0
    - zict==2.0.0
'''

**Comment by marcelned** [comment]
@jacobtomlinson Tried installing `azure-mgmt-network==16.0.0`.

Unfortunately the error persists.
