### ISSUE TITLE
Pulling private image for AzureVMCluster?

### ISSUE THREAD

**Issue by yunlongxu-numagic** [dask/dask-cloudprovider#318]
Originally asked in #93, and opening a new issue as suggested by @jacobtomlinson 

Is it true that `AzureVMCluster` cannot pull private docker images as there are no way to pass in the credentials? 

Apologies if this is actually possible but somehow I overlooked it from the documentation. If it indeed not possible, would it be something on the roadmap? (I assume a solution to pass in docker login credentials would be generic for all cloud providers and hence would also solve #93?)

**Comment by jacobtomlinson** [comment]
Currently, the way to use private Docker images is to use a custom VM image that already has your credentials baked in. See the [docs here on creating custom images with Packer](https://cloudprovider.dask.org/en/latest/packer.html). The example on that page is for AWS so check the packer docs for the Azure equivalent options. You would want to add a `docker login` command to the `cloud-init` file.

Adding a solution or `AzureVMCluster` would be generic for the VM based cluster managers, but #93 is for ECS so it would not apply there.

Adding an option to support logging into docker registries without having to create a custom image sounds like a good idea. I'm wondering if a more generic solution like allowing folks to configure extra bootstrap commands would be more flexible.

**Comment by yunlongxu-numagic** [comment]
@jacobtomlinson thanks for the pointer to Packer, it does look like it will solve my problem.
