### ISSUE TITLE
Local scheduler and cloud workers

### ISSUE THREAD

**Issue by glemaitre** [dask/dask-cloudprovider#32]
I had a quick look at the documentation. It seems that both scheduler and workers are created on the cloud. Would it possible and make sense to have the flexibility to start to the scheduler locally and only have cloud workers?

In short, my current use case would be the following (maybe this is a weird design):
I have a web-frontend linked to a database and I am using a scheduler/dispatcher which is in charge of fetching stuff from the database and start some workers (local or cloud) to make some ML training/testing, get back the results to make some update on the DB.

In this case, having the scheduler next to the DB seems to be meaningful, but to be honest I am not the most knowledgeable person on these types of infrastructure.

**Comment by jacobtomlinson** [comment]
Sorry we never got back to you here.

Given the amount of time that has passed I'm going to close this out, but if this is still a relevant question please comment back here.
