### ISSUE TITLE
Add sleep on GetLogEvents to prevent Rate Limit Exceeded

### ISSUE THREAD

**Issue by kylejn27** [dask/dask-cloudprovider#34]
GetLogEvents has a "10 requests per second per account per Region" limit. https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html

https://github.com/dask/dask-cloudprovider/blob/master/dask_cloudprovider/providers/aws/ecs.py#L270 should pause before polling for the next batch of logs

**Comment by jacobtomlinson** [comment]
Closed in #44
