### ISSUE TITLE
AzureVMCluster not starting scheduler and workers with proper docker_image

### ISSUE THREAD

**Issue by lzalewsk** [dask/dask-cloudprovider#349]
**What happened**:
I am trying to start Dask Cluster on Azure using dask_cloudprovider with my own docker image with following params 
``` python
cluster = AzureVMCluster(
    resource_group=ws.resource_group,
    vnet="dasknet",
    security_group="dask-sg",
    n_workers=1,
    location="eastus",
    docker_image="mcr.microsoft.com/azureml/curated/lightgbm-3.2-ubuntu18.04-py37-cpu:34", #I have my own image extended with some additional python packages i.e. adlfs
    debug=True,
)
```
**What you expected to happen**:
I expected to see in logs
```
docker run --net=host   mcr.microsoft.com/azureml/curated/lightgbm-3.2-ubuntu18.04-py37-cpu:34 env ..
```
insted of 
```
docker run --net=host   daskdev/dask:latest env ..
```
And finaly there is not possible to use adlfs package and read_parquet data from DataLake v2.
(wrong image :( )

**Anything else we need to know?**:

**Environment**:

- dask_cloudprovider: '2022.4.0'
- Python version: 3.8
- Operating System: Ubuntu (VM on Azure)
- az cli version:
``` json
{
  "azure-cli": "2.36.0",
  "azure-cli-core": "2.36.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "ml": "2.3.1"
  }
}
```

<details>
<summary>Cluster Dump State:</summary>
Network interface ready

Cloud init
==========

#cloud-config

# Bootstrap
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - ubuntu-drivers-common

# Enable ipv4 forwarding, required on CIS hardened machines
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

runcmd:
  
  # Install Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker
  

  

  

  # Run container
  - 'docker run --net=host   daskdev/dask:latest env DASK_INTERNAL_INHERIT_CONFIG="ey....==" python -m distributed.cli.dask_spec tls://20.127.101.46:8786 --spec ''{"cls": "dask.distributed.Nanny", "opts": {"name": "dask-b3e518fc-worker-0eaed82d"}}'''

  
  # Shutdown when command is done
  - shutdown -h now
  
Creating VM
with parameters
{
  "hardware_profile": {
    "vm_size": "Standard_DS1_v2"
  },
  "location": "eastus",
  "network_profile": {
    "network_interfaces": [
      {
        "id": "/subscriptions/...../dask-cloudprovider-nic-c3c4eca8"
      }
    ]
  },
  "os_profile": {
    "admin_password": "09cd1bfb....",
    "admin_username": "dask",
    "computer_name": "dask-b3e518fc-worker-0eaed82d",
    "custom_data": "...."
  },
  "storage_profile": {
    "image_reference": {
      "offer": "UbuntuServer",
      "publisher": "Canonical",
      "sku": "18.04-LTS",
      "version": "latest"
    },
    "os_disk": {
      "create_option": "FromImage",
      "disk_size_gb": 50
    }
  },
  "tags": {
    "cluster-id": "b3e518fc",
    "creator": "dask-cloudprovider"
  }
}
Created VM dask-b3e518fc-worker-0eaed82d

---------
logs from cloud-init-output.log from worker node

Setting up docker-ce-rootless-extras (5:20.10.16~3-0~ubuntu-bionic) ...^M
Setting up docker-scan-plugin (0.17.0~ubuntu-bionic) ...^M
Setting up libltdl7:amd64 (2.4.6-2) ...^M
Setting up docker-ce-cli (5:20.10.16~3-0~ubuntu-bionic) ...^M
Setting up pigz (2.4-1) ...^M
Setting up docker-ce (5:20.10.16~3-0~ubuntu-bionic) ...^M
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.^M
Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/systemd/system/docker.socket.^M
Processing triggers for libc-bin (2.27-3ubuntu1.5) ...^M
Processing triggers for systemd (237-3ubuntu10.53) ...^M
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...^M
Processing triggers for ureadahead (0.100.0-21) ...^M
Synchronizing state of docker.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable docker
Unable to find image 'daskdev/dask:latest' locally
latest: Pulling from daskdev/dask
4d32b49e2995: Pulling fs layer
267bae6de278: Pulling fs layer
cd3ab84d6761: Pulling fs layer
181f9e4f703f: Pulling fs layer
084d92a6edad: Pulling fs layer
181f9e4f703f: Waiting
084d92a6edad: Waiting
4d32b49e2995: Verifying Checksum
4d32b49e2995: Download complete
181f9e4f703f: Verifying Checksum

</details>

**Comment by jacobtomlinson** [comment]
Thanks for the report and sorry about the bug. Should be fixed in #350.
