### ISSUE TITLE
EC2Cluster does not wait for workers to complete setup

### ISSUE THREAD

**Issue by pwerth** [dask/dask-cloudprovider#370]
When creating a Fargate cluster, the workers are always already connected to the scheduler by the time the Python code terminates. In other words, running

```
from dask_cloudprovider.aws import FargateCluster
from dask.distributed import Client

cluster = FargateCluster(n_workers=2)
client = Client(cluster)

print(client.scheduler_info())
```

prints the following

```
{
'type': 'Scheduler', 
'id': 'Scheduler-6c912e9c-8183-4c63-83e8-85843cb9a5f7', 
'address': 'tcp://10.130.3.205:8786', 
'services': {'dashboard': 8787}, 
'started': 1660086458.3028746, 
'workers': {
'tcp://10.130.1.126:38345': {'type': 'Worker', 'id': 0,'host': '10.130.1.126', 'resources': {}, 'local_directory': '/dask-worker-space/worker-c0d8ckb2', 'name': 0, 'nthreads': 4, 'memory_limit': 30000000000, 'last_seen': 1660086512.5367937, 'services': {'dashboard': 35847}, 'metrics': {'executing': 0, 'in_memory': 0, 'ready': 0, 'in_flight': 0, 'bandwidth': {'total': 100000000, 'workers': {}, 'types': {}}, 'spilled_nbytes': 0, 'cpu': 0.0, 'memory': 91680768, 'time': 1660086512.035593, 'read_bytes': 14461.13530849508, 'write_bytes': 19720.094084302873, 'read_bytes_disk': 164057.08412573286, 'write_bytes_disk': 0.0, 'num_fds': 23}, 'nanny': 'tcp://10.130.1.126:34587'}, 
'tcp://10.130.1.98:35141': {'type': 'Worker', 'id': 1, 'host': '10.130.1.98', 'resources': {}, 'local_directory': '/dask-worker-space/worker-fqjt3e_n', 'name': 1, 'nthreads': 4, 'memory_limit': 30000000000, 'last_seen': 1660086512.4145467, 'services': {'dashboard': 35127}, 'metrics': {'executing': 0, 'in_memory': 0, 'ready': 0, 'in_flight': 0, 'bandwidth': {'total': 100000000, 'workers': {}, 'types': {}}, 'spilled_nbytes': 0, 'cpu': 2.0, 'memory': 93057024, 'time': 1660086511.9154685, 'read_bytes': 257.58337649675514, 'write_bytes': 964.4400840925017, 'read_bytes_disk': 0.0, 'write_bytes_disk': 0.0, 'num_fds': 23}, 'nanny': 'tcp://10.130.1.98:42127'}}
}
```

Namely, `'workers'` is populated with the two workers I requested. And I can verify by going to the dashboard that they are in fact connected to the scheduler and ready for work.

However, when I create an EC2 cluster, this is not the case. When I run

```
from dask_cloudprovider.aws import EC2Cluster
from dask.distributed import Client

cluster = EC2Cluster(n_workers=2)
client = Client(cluster)

print(client.scheduler_info())
```

the scheduler info that is printed is

```
{
'type': 'Scheduler',
 'id': 'Scheduler-4d5391ff-af0d-49b5-b48c-3cee4d22b483', 
'address': 'tcp://10.130.0.14:8786', 
'services': {'dashboard': 8787}, 
'started': 1660086963.5793185, 
'workers': {}
}
```

This is problematic because if the next line of code in my script wants to perform distributed computation using, say, a dask collection, there won't be any workers available. 

I am not sure if this difference in behavior is intentional or not. If it's not, this seems like a bug that should be fixed. If it is intentional, I'd be curious to know why, and I'd propose adding an argument to `EC2Cluster` like `wait_for_workers` that can be set to `True` to enable this behavior.

In either case I am happy to open a PR to resolve this, but I would appreciate some guidance as I've looked through the code base and it's not clear to me where exactly the difference occurs.

**Comment by jacobtomlinson** [comment]
I don't think we should ever assume that all workers will be ready when the cluster instantiation finishes. If `ECSCluster` guarantees that they are ready every time that is just a coincidence.

Generally, we recommend folks use `Client.wait_for_workers(n)` if they need a certain number of workers before continuing. I'm not sure also adding that method to the `Cluster` object adds much value given that it is already available on the client.

**Comment by pwerth** [comment]
Thanks for the reply! I wasn't familiar with the `wait_for_workers` method but that's exactly what I need.
