### ISSUE TITLE
AzureVMCluster uses deprecated method to get the subscription ID

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask-cloudprovider#376]
Currently `AzureVMCluster` infers the Azure subscription ID with a deprecated method: https://github.com/Azure/azure-sdk-for-python/blob/12fb3daae6a69d99ff67a64ed52a1fb99671836b/sdk/core/azure-common/azure/common/credentials.py#L17-L28

It'd be nice to avoid that. I think that we could add a `subscription_id` argument to `AzureVM.__init__`. We might even want to make it required like `resource_group`. This would match the behavior of the underlying `azure.mgmt` libraries we call into, which all have the subscription ID as a required argument rather than trying to infer it.

**Comment by TomAugspurger** [comment]
I'm looking into the dependencies a bit, and I think this is the current state:

`azure-cli-core` is used to get the default Azure subscription configured for the Azure CLI. Starting with azure-cli-core>=2.21.0`, there doesn't seem to be an officially sanctioned way to get the "default" subscription ID from a Python API. You can call `az account list -o json` in a subprocess and parse the JSON output. But I'm inclined to follow the lead of the Azure Python SDK can just make `subscription_id` a required argument.

I've done some manual testing, and unpinning the other Azure dependencies seems fine. I'm running the azure tests now, and will make a PR if those pass.

**Comment by jacobtomlinson** [comment]
Ah that's a shame! I kinda liked that it used the default subscription from `az` and that you could change your subscription with `az account set`. That way if you create a cluster with `AzureVMCluster` and use `az` to list your VMs they will line up. 

If we require the subscription ID to be set for each cluster they could in theory set a different subscription to whatever `az` is using and result in confusion.

But if getting the default subscription is deprecated and there is alternative I guess it makes sense to follow what the Azure Python SDK is doing.

**Comment by jacobtomlinson** [comment]
_Also it's good you have you around here @TomAugspurger!_

**Comment by TomAugspurger** [comment]
Yeah, it is a shame. If you're ok with a `subprocess` call, this doesn't seem like too much of a maintenance burden:

```python
def _get_default_subscription() -> str:
    out = subprocess.check_output(["az", "account", "list", "--query", "[?isDefault]"])
    accounts = json.loads(out)
    if accounts:
        subscription_id = accounts[0]["id"]
        return subscription_id
    raise ValueError(
        "Could not find a default subscription. "
        "Run 'az account set' to set a default subscription."
    )
```

I'll include that in the PR (I still think being able to override the subscription_id, along with the resource_group, is handy for environments like a docker container where you might not have the Azure CLI installed / configured).

**Comment by jacobtomlinson** [comment]
Yeah that sounds great, would be nice to do this if we can. Totally agree that being able to set this via config makes sense too.

Thanks for looking at this!
