### ISSUE TITLE
Different Values for Memory and memoryReservation for AWS ECS Clusters?

### ISSUE THREAD

**Issue by mattalhonte-srm** [dask/dask-cloudprovider#377]
Heya!  Been looking into the guts of Task Definitions for ECS Clusters in AWS, and I saw that `memoryReservation` seems like a pretty handy one for Data Science workloads (where overall memory usage can vary a lot over the course of a run).  

Basically, it's a Soft Limit - so like if you have a job that mostly consumes 12GB but occasionally spikes to 27, you can set it to `memoryReservation` to, say, 14 and `memory` to 30, and be able to fit more Tasks on each EC2 instance.  https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_memory

Right now they're both set by the `worker_mem` (or `scheduler_mem`)  value you pass to the Dask `ECSCluster` object, but it looks like it wouldn't be too hard to add another argument to add them separately?  https://github.com/dask/dask-cloudprovider/blob/main/dask_cloudprovider/aws/ecs.py#L1246 (I'd try to make a working fork but honestly I'm not confident enough when it comes to knowing my way around the codebase).

Does that seem like it'd be worthwhile and/or feasible?

Thanks!

**Comment by jacobtomlinson** [comment]
Thanks for raising this. In #358 we added support for specifying custom task definitions. I'm hesitant to keep adding more and more arguments, I think this kind of thing is at the point where you should just switch to custom task definitions.
