### ISSUE TITLE
Can we do a release

### ISSUE THREAD

**Issue by quadrupole** [dask/dask-cloudprovider#382]
**Describe the issue**:
I installed via 

```
pip install dask-cloudprovider 
```
Checking my version: 

```
>>> dask_cloudprovider.__version__
'2022.8.0'
```

Now according to the docs and the code in `main`, I expect to be able to supply `scheduler_instance_type` and `worker_instance_type` to `EC2Cluster`, however:

```
>>> EC2Cluster(scheduler_instance_type="t2.micro")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxxxxx/xxxxx/venv/lib/python3.9/site-packages/dask_cloudprovider/aws/ec2.py", line 549, in __init__
    super().__init__(debug=debug, **kwargs)
  File "/Users/xxxxxx/xxxxx/venv/lib/python3.9/site-packages/dask_cloudprovider/generic/vmcluster.py", line 297, in __init__
    super().__init__(**kwargs, security=self.security)
TypeError: __init__() got an unexpected keyword argument 'scheduler_instance_type'
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2022.02.0
- Python version: Python 3.9.13
- Operating System: mac OS Monterey
- Install method (conda, pip, source): pip

**Comment by jacobtomlinson** [comment]
Yup looks like we need to do a release, I'll aim to get one out next week.

**Comment by quadrupole** [comment]
Thanks @jacobtomlinson
