### ISSUE TITLE
Change to Scheduler Address Parsing Breaks TLS Encryption Support

### ISSUE THREAD

**Issue by joeschmid** [dask/dask-cloudprovider#386]
We're still investigating more but we believe this recent PR https://github.com/dask/dask-cloudprovider/pull/373 broke Dask Cloud Provider provisioned clusters on AWS that use TLS encryption. Previously, when the scheduler address was parsed from logs, it would correctly parse the url prefix of `tls://` to indicate the Dask client should use TLS. With the PR, no prefix seems to be included for the scheduler address (the new code in the PR appears to be just `return f"{ip}:{self.port}"`) so the Dask client defaults to assuming `tcp://` for the scheduler address and then fails with:

```
RuntimeError: encryption required by Dask configuration, refusing communication from/to 'tcp://172.29.39.222:8786'
```

Note that the Dask scheduler started with this log output:

```
2022-10-24 12:59:10,760 - distributed.scheduler - INFO - Scheduler at: tls://172.29.39.222:8786
2022-10-24 12:59:10,760 - distributed.scheduler - INFO - dashboard at: :8787
```

We pass the following kwargs to FargateCluster to configure TLS encryption with constants for the Security object and filepaths:

```
        security=SRM_DOCKER_DASK_TLS_SECURITY,
        scheduler_extra_args=[
            "--tls-cert",
            SRM_DOCKER_DASK_TLS_SECURITY.tls_client_cert,
            "--tls-key",
            SRM_DOCKER_DASK_TLS_SECURITY.tls_client_key,
            "--tls-ca-file",
            SRM_DOCKER_DASK_TLS_SECURITY.tls_ca_file,
        ],
        worker_extra_args=[
            "--tls-cert",
            SRM_DOCKER_DASK_TLS_SECURITY.tls_client_cert,
            "--tls-key",
            SRM_DOCKER_DASK_TLS_SECURITY.tls_client_key,
            "--tls-ca-file",
            SRM_DOCKER_DASK_TLS_SECURITY.tls_ca_file,
        ],
```

If you need additional details on environment, etc. please let me know, but this should be easy to recreate and we don't think it's related to anything specifically in our environment. Thanks!

**Comment by jacobtomlinson** [comment]
Thanks for raising this @joeschmid. I expect we should be able to check the `security` kwarg and set the appropriate protocol.

@tamas4sunairio would you be able to take a look?

**Comment by tamas4sunairio** [comment]
Yeah, I think @joeschmid's analysis is right. Sorry about that! It would make sense to me to supply a `tls` argument to the `ECSCluster` class, which would inform whether the `address` property should be prefixed with `tcp://` or `tls://` (are there any other options?)

Alternatively, we could introspect the `scheduler_extra_args` / `worker_extra_args` arguments to check if TLS related configuration is present there.

A middle ground between the two would be to have the extra `tls` argument, AND do the introspection, and log a warning if there's a mismatch.

What do you both think about this?

**Comment by tamas4sunairio** [comment]
I made an implementation of the "middle ground" version above. Let me know what you think! @joeschmid I didn't get a chance to test the TLS part, would you be able to check out the PR and see if that solves the problem?

**Comment by joeschmid** [comment]
@tamas4sunairio thanks so much for the quick turnaround! I like the "middle ground" approach that you went with. We can definitely help to test and confirm that it addresses the issue.
