### ISSUE TITLE
Fargate Support

### ISSUE THREAD

**Issue by rymoore** [dask/dask-cloudprovider#39]
Is the FargateCluster still supported (https://cloudprovider.dask.org/en/latest/#fargate-ecs)? 

I'm attempting to create a cluster and can't seem to find the cloud_provider module:

`No module named 'dask_cloudprovider'`

**Comment by jacobtomlinson** [comment]
Yes it is still supported. It sounds like you're having trouble importing the module all together. How did you install dask-cloudprovider?

**Comment by rymoore** [comment]
@jacobtomlinson - I think that's the problem... I don't see instruction on how to install dask-cloudprovider and have tried `pip install dask-cloudprovider` but got:

`No matching distribution found for dask-cloudprovider`

**Comment by jacobtomlinson** [comment]
That is because we haven't had a release of `dask-cloudprovider` yet. For now you need to install from source.

You can do it with pip like this

```console
$ pip install git+https://github.com/dask/dask-cloudprovider.git
...
```

**Comment by jacobtomlinson** [comment]
I think we should go with a release.

**Comment by jacobtomlinson** [comment]
@rymoore you should now find that `pip install dask-cloudprovider` will work

**Comment by sodre** [comment]
Would it be possible to create a conda-forge package for it as well?

**Comment by jacobtomlinson** [comment]
@sodre `dask-cloudprovider` is now available on conda-forge 😄 🎉

**Comment by sodre** [comment]
thanks @jacobtomlinson !

**Comment by jacobtomlinson** [comment]
Now that we have releases I'm going to close this issue.
