### ISSUE TITLE
[GCP] Set custom service account for worker VMs

### ISSUE THREAD

**Issue by erl987** [dask/dask-cloudprovider#403]
# Requested functionality
**Example use case:** The workers need to download data from Google Cloud Storage. They require the *Cloud Storage Viewer* role for this purpose.

I would like to set a custom service account for the worker VMs that contains this role.

# Current state
As far as I can see, no service account can be set for the worker or scheduler. Instead, I need to add a service account key file (having the required role) to the Docker container of the worker / scheduler and make the environment variable `GOOGLE_APPLICATION_CREDENTIALS` pointing to it in the container. Then for example the Python package `google-cloud-storage` can access the storage buckets from the worker.

This is undesirable, both regarding flexibility and security.

**Comment by jmhatze** [comment]
Having a similar issue, I need to configure a non-default service account for both worker and scheduler VMs to run under. Ideally, the service account would be passed as a keyword argument in the constructor of `GCPCluster`. Would be willing to open a PR to add this functionality.
