### ISSUE TITLE
No New Releases?

### ISSUE THREAD

**Issue by herlma** [dask/dask-cloudprovider#435]
There hasn't been a release to pypi in nearly two years and it looks like the CI here is broken. Dask no longer works with python 3.9 and the current builds / tests are failing when trying to install dask into a python 3.9 environment. Can we roll python envs to no longer support python 3.9 and update the CI / pypi deploys accordingly?

**Comment by jacobtomlinson** [comment]
Version `2024.9.0` is now available on PyPI and supports Python 3.10-3.12. See #436 for further info.
