### ISSUE TITLE
Required permissions policies to attach to IAM user

### ISSUE THREAD

**Issue by filippo82** [dask/dask-cloudprovider#49]
Hi all,

I am fairly new to the AWS world and I've decided to reproduce the results in @jacobtomlinson [blog post](https://medium.com/rapids-ai/getting-started-with-rapids-on-aws-ecs-using-dask-cloud-provider-b1adfdbc9c6e#cid=av01_so-twit_en-us). To do so, I first had to create a new IAM user (I thought it would be better to create a specific user to test dask-cloudprovider) without attaching any specific permissions policy. Then, after trying to execute `cluster = FargateCluster(n_workers=1)`, I experienced the first permissions issue:

> AccessDeniedException: An error occurred (AccessDeniedException) when calling the ListClusters operation: User: arn:aws:iam::707249732839:user/filippoawstest is not authorized to perform: ecs:ListClusters on resource: *

I *think* I solved this adding the AWS managed policy **AmazonECS_FullAccess**.

The second issue I had was:

> ClientError: An error occurred (AccessDenied) when calling the ListRoleTags operation: User: arn:aws:iam::707249732839:user/filippoawstest is not authorized to perform: iam:ListRoleTags on resource: role AWSServiceRoleForECS

I *think* I solved this adding the AWS managed policy **IAMFullAccess**.

The third issue I had was:

> An error occurred (UnauthorizedOperation) when calling the CreateTags operation: You are not authorized to perform this operation. Encoded authorization failure message: LONG_MESSAGE

After decoding the error message (`aws decode-authorization-message --encoded-message LONG_MESSAGE`), I believe it was related to this action `'action': 'ec2:CreateTags`. Again, I *think* I solved this adding the AWS managed policy **CloudWatchLogsReadOnlyAccess**.

After adding these policies, `cluster = FargateCluster(n_workers=1)` succeeded and produced this message:

> /work/bfilippo/miniconda3/envs/aws/lib/python3.7/contextlib.py:119: UserWarning: Creating your cluster is taking a surprisingly long time. This is likely due to pending resources on AWS. Hang tight! next(self.gen)

Then, the remaining of the simple dask array example worked (I could see that through the dashboard too):
```
import dask.array as da
arr = da.random.random((1000, 1000, 10000), chunks=(100, 100, 1000))
arr = arr.mean().persist()
arr.compute()
```

I didn't play with the ECS Cluster part.

**So my question is: Is there a better set of policies to attach to the user?**

Cheers.
-Filippo

**Comment by jacobtomlinson** [comment]
It looks like you took a reasonable approach to figuring this out.

Adding `AmazonECS_FullAccess`, `IAMFullAccess` and `CloudWatchLogsReadOnlyAccess` should definitely get you up and running, and it looks like it did.

We should probably put together a minimum policy that we would require to use FargateCluster in the docs following the [principle of least privilege](https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#grant-least-privilege).

**Comment by filippo82** [comment]
I also add to add this policy to decode the error message:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": ["sts:DecodeAuthorizationMessage"],
      "Resource": ["*"]
    }
  ]
}
```

**Comment by mrocklin** [comment]
Thanks for raising this issue @filippo82 .  I just ran down the same path and have similar questions.

After adding the policies mentioned above I still have some problem creating tags

```python-traceback
In [1]: from dask_cloudprovider import FargateCluster                                                    
cl
In [2]: cluster = FargateCluster()                                                                       
---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
<ipython-input-2-daa8d8d1d8ee> in <module>
----> 1 cluster = FargateCluster()

~/workspace/dask-cloudprovider/dask_cloudprovider/providers/aws/ecs.py in __init__(self, **kwargs)
   1099 
   1100     def __init__(self, **kwargs):
-> 1101         super().__init__(fargate_scheduler=True, fargate_workers=True, **kwargs)
   1102 
   1103 

~/workspace/dask-cloudprovider/dask_cloudprovider/providers/aws/ecs.py in __init__(self, fargate_scheduler, fargate_workers, image, scheduler_cpu, scheduler_mem, scheduler_timeout, worker_cpu, worker_mem, worker_gpu, n_workers, cluster_arn, cluster_name_template, execution_role_arn, task_role_arn, task_role_policies, cloudwatch_logs_group, cloudwatch_logs_stream_prefix, cloudwatch_logs_default_retention, vpc, subnets, security_groups, environment, tags, find_address_timeout, skip_cleanup, aws_access_key_id, aws_secret_access_key, region_name, **kwargs)
    593         self._region_name = region_name
    594         self._lock = asyncio.Lock()
--> 595         super().__init__(**kwargs)
    596 
    597     async def _start(self,):

~/miniconda/envs/cloudprovider/lib/python3.8/site-packages/distributed/deploy/spec.py in __init__(self, workers, scheduler, worker, asynchronous, loop, security, silence_logs, name)
    255         if not self.asynchronous:
    256             self._loop_runner.start()
--> 257             self.sync(self._start)
    258             self.sync(self._correct_state)
    259 

~/miniconda/envs/cloudprovider/lib/python3.8/site-packages/distributed/deploy/cluster.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    158             return future
    159         else:
--> 160             return sync(self.loop, func, *args, **kwargs)
    161 
    162     async def _logs(self, scheduler=True, workers=True):

~/miniconda/envs/cloudprovider/lib/python3.8/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    343     if error[0]:
    344         typ, exc, tb = error[0]
--> 345         raise exc.with_traceback(tb)
    346     else:
    347         return result[0]

~/miniconda/envs/cloudprovider/lib/python3.8/site-packages/distributed/utils.py in f()
    327             if callback_timeout is not None:
    328                 future = asyncio.wait_for(future, callback_timeout)
--> 329             result[0] = yield future
    330         except Exception as exc:
    331             error[0] = sys.exc_info()

~/miniconda/envs/cloudprovider/lib/python3.8/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/workspace/dask-cloudprovider/dask_cloudprovider/providers/aws/ecs.py in _start(self)
    720             self._security_groups = (
    721                 self.config.get("security_groups")
--> 722                 or await self._create_security_groups()
    723             )
    724 

~/workspace/dask-cloudprovider/dask_cloudprovider/providers/aws/ecs.py in _create_security_groups(self)
    948             DryRun=False,
    949         )
--> 950         await self._clients["ec2"].create_tags(
    951             Resources=[response["GroupId"]], Tags=dict_to_aws(self.tags, upper=True)
    952         )

~/miniconda/envs/cloudprovider/lib/python3.8/site-packages/aiobotocore/client.py in _make_api_call(self, operation_name, api_params)
    100             error_code = parsed_response.get("Error", {}).get("Code")
    101             error_class = self.exceptions.from_code(error_code)
--> 102             raise error_class(parsed_response, operation_name)
    103         else:
    104             return parsed_response

ClientError: An error occurred (UnauthorizedOperation) when calling the CreateTags operation: You are not authorized to perform this operation. Encoded authorization failure message: xT8_MaMyQLHWBEAXot70_bhchagKYlc0_MqlAHSm8oIxwz6ShFvIsc1NEFO3uBW_8lG5_TIg1bCy8o0oXnt1JqyCEuyi0HkAW1sLF95WHd4RPUyaQ8JpI4zwFAHtPjR3sLjy2bciuFh5JSPtbrcKf-7uVycoHl6fKidE2oLKYcnNhUkWU152DMAEqSCC08W2WpHMRYRvRLZZjjv8j442IlXIZt-rcbyh8dSzECPX-tLL3csXOV38vXXi3YElNx3ZCXOU09bpDBMiKLgbRW4P61N625g-xFgq5Ylvss_RXJWK7Z1lo5cg9WycD4Y7z4_YlEinAxI0YAHSaKTOoNwmHA6NJUNiUwAnu5As3nzEKbUA9NS6TNyqDV3XCVl5vUHb01su5U1UFHToq-LuAPorb6uCkphtUZ3ZikCmK6YQ6aRfydbZbEU38zvVXWHZ9UVmebre6zS1c_K800tDCUhuv8dbAlWWUheVCr6aqn5V0AM5NmtQg9bENsTrb5rSCAslJq_vKuFnVw50JS2yxQiPzRBxbLZQoHqMUC3mJXE6mg5iJ-yK_reao3DHw0VtS9vkkaiDR_I
```

**Comment by mrocklin** [comment]
Removing the create_tags code lets me move forward.  My guess is that this code was added recently?  

> We should probably put together a minimum policy that we would require to use FargateCluster in the docs following the principle of least privilege.

I went searching for this in the docs actually.

**Comment by filippo82** [comment]
Hi @mrocklin, I haven't tried this again since December but I should be able to test it again in the next weeks. I'll update here if I see a different behaviour from last time.

**Comment by rsignell-usgs** [comment]
@zacflamig, @jkmacc-LANL and I working on improving dask-cloudprovider doc here at the Dask developers workshop. 

Do you by chance know how to create the minimal role that would be required to create a Fargate cluster from SageMaker?

**Comment by NicWayand** [comment]
Hey @mrocklin, I am reproducing your error (UnauthorizedOperation) after adding the FullAccess policies above. Can you provide more detail on your work around to remove the create_tages code? (I assume just removing this line? https://github.com/dask/dask-cloudprovider/blob/d441f5b95a85ac731c35420489b6df14fa2883ab/dask_cloudprovider/providers/aws/ecs.py#L950)

**Comment by rsignell-usgs** [comment]
It was suggested that the way to figure out the minimal policy would be to enable basically everything, then use CloudTrail to figure out what was really used.    So we added these policies:

![2020-02-28_12-13-19](https://user-images.githubusercontent.com/1872600/75582749-3e6aa180-5a3a-11ea-91b8-4cac02e2111d.png)

Then captured the CloudTrail events from the time period just before we called `FargateCluster` to just after we destroyed the cluster:

![2020-02-28_12-50-05](https://user-images.githubusercontent.com/1872600/75582858-812c7980-5a3a-11ea-9185-70ec19f21d6e.png)

We saved the events as JSON and then used [trailscraper](https://pypi.org/project/trailscraper/) to create an IAM policy from these events. 

This didn't work perfectly (not sure why), but it was a good start.   From there we just tried starting a cluster and adding each action one-by-one until it worked:

```json
{
    "Statement": [
        {
            "Action": [
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:CreateSecurityGroup",
                "ec2:CreateTags",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DescribeSubnets",
                "ec2:DescribeVpcs",
                "ec2:DeleteSecurityGroup",
                "ecs:CreateCluster",
                "ecs:DescribeTasks",
                "ecs:ListAccountSettings",
                "ecs:RegisterTaskDefinition",
                "ecs:RunTask",
                "ecs:StopTask",
                "ecs:ListClusters",
                "ecs:DescribeClusters",
                "ecs:DeleteCluster",
                "ecs:ListTaskDefinitions",
                "ecs:DescribeTaskDefinition",
                "ecs:DeregisterTaskDefinition",
                "iam:AttachRolePolicy",
                "iam:CreateRole",
                "iam:TagRole",
                "iam:PassRole",
                "iam:DeleteRole",
                "iam:ListRoleTags",
                "iam:ListAttachedRolePolicies",
                "iam:DetachRolePolicy",
                "logs:DescribeLogGroups"
            ],
            "Effect": "Allow",
            "Resource": [
                "*"
            ]
        }
    ],
    "Version": "2012-10-17"
}
```

**Comment by jacobtomlinson** [comment]
Thanks so much for taking this time to figure this out @rsignell-usgs!

**Comment by jacobtomlinson** [comment]
You could totally expand your comment into a blog post on "How to find out what IAM permissions a third party tool requires".

**Comment by NicWayand** [comment]
Thank you @rsignell-usgs! Working for me now. Very useful to know about CloudTrail!

**Comment by filippo82** [comment]
This was very interesting! Thank you.

**Comment by Ieshu** [comment]
I am creating an ETL pipeline wherein the data from S3 has to be sent to redshift table. To do so , I have trying to create redshift cluster using the below code.

# Define the cluster parameters used to create cluster in redshift
cluster_parameters = {
    'ClusterIdentifier': 'dwhCluster',
    'NodeType': 'dc2.large',
    'MasterUsername': 'myawsuser',
    'MasterUserPassword': 'Password13',
    'DBName': 'mydatabase',
    'ClusterType': 'single-node',
    'NumberOfNodes': 1,
    'PubliclyAccessible': True,
    'VpcSecurityGroupIds': 'sg-096828141a43d4af9', 
    'AvailabilityZone': 'ap-south-1a', 
    'Port': 5439,
    'ClusterSubnetGroupName': 'my-subnet-group'   
}

#finally create cluster in redshift by passing cluster parameter

import boto3

# Create a Redshift client
redshift_client = boto3.client('redshift', 
                               aws_access_key_id=KEY, 
                               aws_secret_access_key=SECRET)

# Create the cluster
try:
    response = redshift_client.create_cluster(**cluster_parameters)
    print('Redshift cluster creation initiated.')
except redshift_client.exceptions.ClusterAlreadyExistsFault:
    print('Cluster already exists. Skipping cluster creation.')
    # You can choose to exit the program or perform other actions as needed
    # exit()

However I have been getting an error 

# UnauthorizedOperation: An error occurred (UnauthorizedOperation) when calling the CreateCluster operation: Access Denied. Please ensure that your IAM Permissions allow this operation.

I have checked my IAM User and all the added policies with it, along with that I have also edited the permissions defined in my policy JSON.  This is my updated JSON for all Redshift actions 

{
			"Effect": "Allow",
			"Action": [
				"redshift:CreateCluster",
				"redshift:DescribeClusters",
				"redshift:ModifyCluster",
				"redshift:DeleteCluster",
				"redshift:CreateClusterSubnetGroup",
				"redshift:AuthorizeClusterSecurityGroupIngress",
				"redshift:CreateClusterParameterGroup"
			],
			"Resource": "*"
}
I have also used IAM console to check the same and it seems that my IAM user glue_ies has the Create_bucket policy attached, and the policy appears to be correctly associated with the IAM user.

Given that the IAM policy includes the necessary permissions for S3 (s3:GetObject), the IAM user has the Create_bucket policy attached, and the AWS CLI configuration is correct

Here are the policies and their attached services

[cloudshell-user@ip-10-132-41-186 ~]$ aws iam get-policy --policy-arn arn:aws:iam::935670829844:policy/Create_bucket
{
    "Policy": {
        "PolicyName": "Create_bucket",
        "PolicyId": "ANPA5TWST2MKCAEISE3IY",
        "Arn": "arn:aws:iam::935670829844:policy/Create_bucket",
        "Path": "/",
        "DefaultVersionId": "v16",
        "AttachmentCount": 1,
        "PermissionsBoundaryUsageCount": 0,
        "IsAttachable": true,
        "CreateDate": "2023-11-28T22:12:12+00:00",
        "UpdateDate": "2023-12-05T21:40:19+00:00",
        "Tags": []
    }
}
[cloudshell-user@ip-10-132-41-186 ~]$ aws iam list-user-policies --user-name glue_ies
{
    "PolicyNames": [
        "redshift_policy"
    ]
}
[cloudshell-user@ip-10-132-41-186 ~]$ aws iam list-attached-user-policies --user-name glue_ies
{
    "AttachedPolicies": [
        {
            "PolicyName": "AWSGlueServiceRole",
            "PolicyArn": "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"
        },
        {
            "PolicyName": "AmazonKinesisAnalyticsFullAccess",
            "PolicyArn": "arn:aws:iam::aws:policy/AmazonKinesisAnalyticsFullAccess"
        },
        {
            "PolicyName": "AmazonDynamoDBFullAccess",
            "PolicyArn": "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
        },
        {
            "PolicyName": "AmazonSageMakerFullAccess",
            "PolicyArn": "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
        },
        {
            "PolicyName": "glue_full",
            "PolicyArn": "arn:aws:iam::935670829844:policy/glue_full"
        },
        {
            "PolicyName": "AmazonSageMaker-ExecutionPolicy-20220515T014505",
            "PolicyArn": "arn:aws:iam::935670829844:policy/service-role/AmazonSageMaker-ExecutionPolicy-20220515T014505"
        },
        {
            "PolicyName": "AmazonSageMaker-ExecutionPolicy-20220515T011355",
            "PolicyArn": "arn:aws:iam::935670829844:policy/service-role/AmazonSageMaker-ExecutionPolicy-20220515T011355"
        },
        {
            "PolicyName": "Create_bucket",
            "PolicyArn": "arn:aws:iam::935670829844:policy/Create_bucket"
        }
    ]
}

Can anyone help me debug this ?
