### ISSUE TITLE
Failed to find scheduler ip address after 30 seconds

### ISSUE THREAD

**Issue by jkmacc-LANL** [dask/dask-cloudprovider#50]
Hi, all.  Thank you for baking some hard-fought AWS knowledge into this library for the benefit of us less-experienced users:-)  I'm very excited to try it out.  

I'm getting a `TimeoutException` trying to make a `FargateCluster`, and I'm not sure how to diagnose it.  I've tweaked the timing parameters on the class, trying to give myself a bit more time, but I've not been successful.   Any help in diagnosing is most welcomed.

```python
In [9]: cluster = FargateCluster(environment={'EXTRA_CONDA_PACKAGES': 'obspy xarray zarr -c conda-forge'}, scheduler_timeout='5 minutes')
---------------------------------------------------------------------------
TimeoutException                          Traceback (most recent call last)
<ipython-input-9-943a4af06ce9> in <module>
----> 1 cluster = FargateCluster(environment={'EXTRA_CONDA_PACKAGES': 'obspy xarray zarr -c conda-forge'}, scheduler_timeout='5 minutes')

... <skipped for brevity> ...

~/miniconda3/envs/xarray/lib/python3.7/site-packages/dask_cloudprovider/providers/aws/ecs.py in _set_address_from_logs(self)
    154             30, "Failed to find %s ip address after 30 seconds." % self.task_type
    155         )
--> 156         while timeout.run():
    157             async for line in self.logs():
    158                 for query_string in ["worker at:", "Scheduler at:"]:

~/miniconda3/envs/xarray/lib/python3.7/site-packages/dask_cloudprovider/utils/timeout.py in run(self)
     72                 return False
     73             else:
---> 74                 raise self.exception
     75         return True
     76

TimeoutException: Failed to find scheduler ip address after 30 seconds.
```

EDIT: grammar

**Comment by jacobtomlinson** [comment]
Thanks for raising this.

I would recommend increasing the `find_address_timeout` and see if that resolves your issue. This could be related to your extra packages taking a while to install.

```python
cluster = FargateCluster(environment={'EXTRA_CONDA_PACKAGES': 'obspy xarray zarr -c conda-forge'}, scheduler_timeout='5 minutes', find_address_timeout=600) 
```

You may also want to watch the logs in the Fargate console to see if there are any issues in creating the scheduler task.

**Comment by jkmacc-LANL** [comment]
Thank you for the suggestion.  I was using `0.1.0`, which doesn't have this keyword.  I switched to using `master`, and got past the error.  Currently, my web proxy won't allow to _actually_ connect to the cluster, so I'll try the rest later (unless you know a workaround).  Thank you for your help!  I think the Issue has been addressed.

**Comment by jacobtomlinson** [comment]
I've just pushed out `0.1.1` which has this change in.

I'm afraid distributed doesn't currently support web proxies.
