### ISSUE TITLE
Fargate dask cluster - dashboard URL is not working

### ISSUE THREAD

**Issue by sublimotion** [dask/dask-cloudprovider#52]
I have been able to deploy a fargate dask cluster but I am not able to access the dask status webpage.

I noticed that the dask cloud provider doesn't create any fargate services which might be the reason the dashboard is not accessible via the public IP.

Are there any configurations needed in order to make the dask status dashboard accessible?

**Comment by jacobtomlinson** [comment]
There is no need to create a service as the scheduler is exposed at a public IP. You should just be able to access the dashboard at `dashboard_address`.

**Comment by jacobtomlinson** [comment]
Closing due to lack of response.
