### ISSUE TITLE
Launching a FargateCluster with less than 1024 CPUs has wrong number of nthreads

### ISSUE THREAD

**Issue by gvelchuru** [dask/dask-cloudprovider#53]
I was launching a FargateCluster with 512 CPUs (.5 vCPUs) and I noticed the nthreads was 0 (which defaults to 2 in Fargate) -- I think this line in the FargateCluster constructor is the offender:

 "--nthreads", "{}".format(int(self._cpu / 1024)),

**Comment by gvelchuru** [comment]
I have opened #54 as a potential solution.

**Comment by jacobtomlinson** [comment]
Thanks for raising this. 

While your fix in #54 seems reasonable I would generally advise against giving a worker less then 1 CPU core.

Perhaps @mrocklin could advise whether there may be some trouble with doing this?

**Comment by mrocklin** [comment]
No trouble technically.  Dask is usually used in compute heavy tasks
though, so this is rare and feels a bit odd.  I'm sure that valid use cases
exist though.

**Comment by jacobtomlinson** [comment]
Thanks @mrocklin and thanks @gvelchuru for putting in a fix.

I'd be curious to hear more about your use cases where you are using <1 vCPU. Just for context.

**Comment by gvelchuru** [comment]
I had a task that was memory-bound rather than CPU-bound, so I found it better to launch many instances with 1GB ram and .256GB CPU. Not sure if this is a one-off case though, since I ended up optimizing the graph and making the task CPU-bound.
