### ISSUE TITLE
How quickly can we spin up a Dask worker on ECS?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-cloudprovider#66]
I'm curious how quickly we can spin up a Dask worker on ECS in optimal conditions.

To reduce docker image size, we might use something like https://github.com/jcrist/alpine-dask-docker .  We might also put this on ECR?

My experience is that this still takes something like 60s.  I'm curious how this changes if we're not using Fargate, but instead happen to have some EC2 instances on standby.  Does the machinery to spin up an ECS Task still take 60s or so, or is it faster than this?

Also, it might be interesting to see how much of this time is our own setup of security groups, roles, and so on, and the extent to which those operations might be made to run concurrently.

**Comment by jacobtomlinson** [comment]
There are multiple layers here, each of which has a time associated but can be cached. Here are some approximate estimations.

- Start VM (1-4 minutes)
- Pull Docker image (10 seconds - 10 minutes)
- Start container (1 second -10 seconds)

Pulling the docker image can vary wildly depending on the size of the image and how it has been compressed. Some of the older multi-GB Pangeo docker images can take ~25 minutes to decompress.

When using Fargate you will likely feel all of these delays as AWS manage everything behind the scenes and seem to have no caching.

However with ECS there are things we can do to improve these times:

- VMs can be kept warm but having redundant capacity, therefore tasks will get placed within seconds. However this warm capacity costs money.

- Being thoughtful about conda environments can help keep container images small

- AMIs can have docker images pre-baked into them. A routine job would need to update the AMI with new images, and thought needs to be put into what images should be baked into every time as disk space costs money.

- Docker images can be built without compression. This should also speed up pull times.

Therefore to answer the original question with all of these improvements **an individual worker could be started in < 10 seconds**, however once the warm infrastructure has been exhausted this will increase to ~5 minutes.

**Comment by mrocklin** [comment]
Thanks @jacobtomlinson !
