### ISSUE TITLE
Do we expose workers to the open internet?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-cloudprovider#76]
Looking through the codebase I don't see any differentiating between workers and scheduler tasks when it comes to exposing public network access.  The security group exposes ports 8786:8787 to all addresses, and the network configuration specified when we run a task includes `"assignPublicIp": "ENABLED"` if we're in fargate mode.  

Does this mean that workers are exposed on ports 8786:8787?  In the rare case where the worker chooses one of these ports is it publicly accessible somehow?

**Comment by jacobtomlinson** [comment]
Yes the workers are exposed with the same policies as the scheduler. This was due to a limitation in Fargate where we couldn't mix public and private subnets for some reason. This may well be fixed now and can be resolved.

I was under the impression that Dask workers would never select ports this low?

**Comment by mrocklin** [comment]
I think that Dask Workers select random ports by default.  I believe that the OS will select anything above 1024.  

We could also specify the port?

```
dask-worker ... --port 8989
```

Could we make two security groups?  One for everyone (open access on internal network) and one only for the scheduler (public access on a couple of ports).  Or alternatively, could we turn off the assignPublicIP option for worker tasks?

**Comment by jacobtomlinson** [comment]
Ideally we would turn off `assignPublicIP` as there is no need for workers to have one. I struggling to fully remember what the issue was with this.
