### ISSUE TITLE
worker denied permission to S3 requester pays

### ISSUE THREAD

**Issue by rsignell-usgs** [dask/dask-cloudprovider#83]
I'm creating a `FargateCluster` and when I read public buckets, everything works fine, but when I try to read a requester pays bucket (where my credentials are obviously needed), the workers are failing. 

Here's a worker log:
https://gist.github.com/rsignell-usgs/d9171c73aaecef625aed88d9a8802aee

Is this just user error on my part, missing something from the Docker image or from the policy I added to the `AmazonSageMaker-ExecutionRole`?

Or is this an actual issue for this or some other package?

**Comment by mrocklin** [comment]
I wonder if @kylejn27 knows enough to give a quick answer here?

**Comment by kylejn27** [comment]
I'm 90% certain this is an AWS permissions issue. Clued in by the below error from your logs 
```
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```

I'm not super familiar with Requester Pays Buckets but I'd troubleshoot by trying to read from that bucket using the awscli on the instance that your workers are running on. Removing layers of abstraction can be helpful for this kind of thing

**Comment by rsignell-usgs** [comment]
I was able to solve this by providing the `AmazonS3FullAccess` policy to the workers:
```
cluster = FargateCluster(n_workers=1, image='rsignell/fargate-worker:2020-04-14f', 
                         scheduler_timeout='20 minutes', 
                         task_role_policies=['arn:aws:iam::aws:policy/AmazonS3FullAccess']
```
