### ISSUE TITLE
Connecting to ECS + EC2 Cluster fails due to memory error

### ISSUE THREAD

**Issue by JulianWgs** [dask/dask-cloudprovider#86]
Hello everyone,

I'm trying to connect to a ECS + EC2 cluster with two c5.large nodes.

Unfortunately I get this error message:
```python
{'tasks': [],
 'failures': [{'arn': 'XXX:XXX:XXX:XX-XXXXXXX-X:XXXXXXXXXXXX:XXXXXXXXX-XXXXXXXX/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX',
   'reason': 'RESOURCE:MEMORY'},
  {'arn': 'XXX:XXX:XXX:XX-XXXXXXX-X:XXXXXXXXXXXX:XXXXXXXXX-XXXXXXXX/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX',
   'reason': 'RESOURCE:MEMORY'}],
 'ResponseMetadata': {'RequestId': 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amzn-requestid': 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX',
   'content-type': 'application/x-amz-json-1.1',
   'content-length': '287',
   'date': 'XXX, XX XXX XXXX XX:XX:XX XXX'},
  'RetryAttempts': 0}}
```

The instance type has 4GB memory, which should be enough.

With best regards
Julian

**Comment by martindurant** [comment]
You may want to look at the configs in https://github.com/dask/dask-cloudprovider/blob/master/dask_cloudprovider/cloudprovider.yaml , where the workers need 16384 MB and the scheduler 4096MB, by default. You will also need some overhead for running the OS.

**Comment by JulianWgs** [comment]
Thanks Martin,

I didn't see the default settings!

Greetings :)
