### ISSUE TITLE
Tracking adoption of AzureMLClass

### ISSUE THREAD

**Issue by drabastomek** [dask/dask-cloudprovider#87]
Hello,

We'd like to add a minimal logging capability to the `AzureMLCluster`. This would only report the following name-value pair: `{"AzureMLCluster-Dask": "0.1"}` (or whatever the current version is) with the AzureML Service and nothing else -- once the cluster is instantiated NO information of what the users do on the Dask Cluster or anything else would be logged.

The only use of this signal would be to account for the adoption of the `AzureMLClass`: how many jobs were submitted to AzureML using the `AzureMLCluster`, how many users used it, how many core-hours it generated. All these information would only be used in an aggregated form.

We have a solution ready to go just looking for your agreement that the above is OK.

**Comment by drabastomek** [comment]
The only change to the original code would be the following

```
try:
    from azureml._base_sdk_common.user_agent import append  
    append('AzureMLCluster-DASK', '0.1')
except:
    pass
```

**Comment by martindurant** [comment]
I assume this will appear in the ongoing work of https://github.com/dask/dask-cloudprovider/pull/67 ?

The matter has been discussed at the dask developers' weekly meeting, and if no concerns are raised here within 24hr, you can take it as agreed to and close this issue.

**Comment by TomAugspurger** [comment]
One comment (I think from @jcrist) was that it's fine to have this be
opt-out.

It'd also be great to have a documentation page somewhere outlining exactly
what's collected and why.

**Comment by jrbourbeau** [comment]
Thanks for raising this issue @drabastomek. In general, logging the version of `dask-cloudprovider` used seems reasonable and would be a valuable piece of information to have.

IIUC we don't log this type of information with other cluster managers (e.g. `FargateCluster` doesn't log this information with AWS). Would you be okay adding some documentation so users are aware of what is being logged and some way for users to opt out if they don't want to send this information (e.g. adding a `log_version`, or some other name, which can be set to `False`)?

**Comment by drabastomek** [comment]
@martindurant that is correct -- this is part of the #67 PR.
@TomAugspurger @jrbourbeau Totally fine to make this opt-out. Will update the documentation and provide an opt-out mechanism. 

Thank you all!

**Comment by drabastomek** [comment]
The opt-out mechanism has been implemented.
