### ISSUE TITLE
`_cleanup_stale_resources()` deregisters unrelated ECS task definitions

### ISSUE THREAD

**Issue by joeschmid** [dask/dask-cloudprovider#94]
We observe that Dask Cloud Provider deregisters ECS task definitions that it did not create. This screenshot shows task definitions that:

1. Dask Cloud Provider did not create
2. Do not get marked as INACTIVE (i.e. unregistered) when Dask Cloud Provider hasn't been run

![image](https://user-images.githubusercontent.com/2823453/80852098-d11eec80-8bf3-11ea-8e4d-da8508cd1dfd.png)

We haven't fully characterized this, but it appears that the current version of `_cleanup_stale_resources()` is too aggressive in its de-registering of task definitions.

**Comment by martindurant** [comment]
That's a bit of a surprise!
Did you have a chance to diagnose the source of the behaviour?

**Comment by jacobtomlinson** [comment]
Ouch sorry about this!

We only clean up task definitions which have the Dask cloudprovider tags.

https://github.com/dask/dask-cloudprovider/blob/master/dask_cloudprovider/providers/aws/ecs.py#L1222-L1224

I'm curious to know whether your task definitions have the same tags. Or whether there is an issue with boto where it is not filtering by tags correctly.

**Comment by joeschmid** [comment]
@jacobtomlinson No worries, not a big deal. We now run with `skip_cleanup=True` to avoid this.

I haven't had a chance to fully characterize it, but it seemed like the search wasn't respecting tags. From what we saw it should be easy to reproduce -- just have another task definition in an existing cluster, then pass that cluster's ARN to have Dask Cloud Provider create resources in that cluster.

Here's a screenshot of one of our task definitions that would always get de-registered when we didn't use `skip_cleanup=True`. You can see that it doesn't have any tags associated with it:

![image](https://user-images.githubusercontent.com/2823453/83762194-46436e80-a645-11ea-9d06-f06a008d53cb.png)

**Comment by jacobtomlinson** [comment]
Thanks for the info. It would be good to get this resolved.

**Comment by capdevc** [comment]
@jacobtomlinson 

This bit a user of dask-cloudprovider at my company. I don't think the tags on task definitions are being checked in the same way that they are on clusters.

from: https://github.com/dask/dask-cloudprovider/blob/64aad0b702a9aa309d0de22b568a58e0199e711c/dask_cloudprovider/providers/aws/ecs.py#L1258-L1274

It looks like any task without a tag for "cluster" (line 1265) matches line 1269 and gets deregistered. If all that's supposed to happen is checking for tasks tagged with a cluster not in the active list, then it's a pretty easy local fix right in that code block to flip the None check and or. I assume it's supposed to be checking for the `DEAFULT_TAGS` as well?

**Comment by jacobtomlinson** [comment]
Thanks @capdevc. Only task definitions created by dask-cloudprovider should be deleted.

I would much appreciate a PR to fix this.

**Comment by AndrewHannigan** [comment]
@jacobtomlinson @martindurant I have an open PR for this when you have a chance to review.
