### ISSUE TITLE
ValueError: Attempt to open non key-like path: /part.0.parquet

### ISSUE THREAD

**Issue by asmith26** [dask/dask-cloudprovider#96]
**Summary**: Reading parquets from AWS s3, then writing them straight back to s3, then re-reading the new parquets causes an error.

## Setup:

```python
from dask.distributed import Client
from dask_cloudprovider import FargateCluster

cluster = FargateCluster(cloudwatch_logs_group="my_log_group",
                         cluster_name_template='as',
                         scheduler_timeout="1 hour",
                         n_workers=1,

                         security_groups=["MY CUSTOM SECURITY GROUP"],
                         task_role_arn='ROLE WITH S3 FULL ACCESS',
                         image="CUSTOM IMAGE ON ECR"
                        )
client = Client(cluster)
```

Libraries include:
```
dask                      2.16.0                   pypi_0    pypi
dask-cloudprovider        0.2.0                    pypi_0    pypi
dask-labextension         2.0.2                    pypi_0    pypi
distributed               2.16.0                   pypi_0    pypi
fastparquet               0.4.0                    pypi_0    pypi
fsspec                    0.7.3                    pypi_0    pypi
python                    3.7.6           h8356626_5_cpython    conda-forge
s3fs                      0.4.2                    pypi_0    pypi
```

And when I run `client.get_versions(check=True)` it indicates no problems with mismatching versions.

## Error:
```python
import dask.dataframe as dd
ddf = dd.read_parquet('s3://PARQUET DIR')
ddf.compute()  # works fine

ddf.to_parquet('s3://ANOTHER PARQUET DIR')
ddf = dd.read_parquet('s3://ANOTHER PARQUET DIR')
ddf.compute()  # fails with error
```

In particular, when I run `cluster.get_logs()`:
```
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((<function safe_head at 0x7f15c16b1170>, (<function read_parquet_part at 0x7f15c165bcb0>, <function FastParquetEngine.read_partition at 0x7f15b35c7200>, <s3fs.core.S3FileSystem object at 0x7f15b35d6a10>, Empty DataFrame
Columns: [x, y]
Index: [], [0], ['x', 'y'], ['index'], {'pf': ('/part.0.parquet', None), 'categories': {}}), 5))
kwargs:    {}
Exception: ValueError('Attempt to open non key-like path: /part.0.parquet')
```

(I've provided an example for part.0.parquet, but it repeats for each part file)

**Comment by martindurant** [comment]
This does not look particularly like a cloudprovider problem. Perhaps can you try with a small part of the data from a single local session to take the cloud infrastructure out of the equation.
Aside from that, it's tricky to say - what kind of path is "ANOTHER PARQUET DIR"? The error seems to suggest that it is only a partial path.

**Comment by asmith26** [comment]
Many thanks for your response @martindurant 

I am having a similar problem running this locally with the distributed scheduler (when I tried the default threaded scheduler it worked though...). I'll investigate further and raise an issue there if required.

**Comment by martindurant** [comment]
> when I tried the default threaded scheduler it worked though

I wonder if "volatile" in this case might just mean "in other processes", then. You might want to try if adding `storage_options={"use_listings_cache": False}` to the parquet calls.

**Comment by asmith26** [comment]
It worked!! Thanks very much for the suggestion and all your help :)
