### ISSUE TITLE
Jupyter environment should have the Dask extension installed

### ISSUE THREAD

**Issue by lostmygithubaccount** [dask/dask-cloudprovider#98]
The Jupyter environment started on the headnode should have the Dask extension installed

**Comment by FredFLi** [comment]
jupyter notebook is started on head node. The head node and all "worker" node have the same env which is user-specified or default one. do you mean we should add dask extension to the env for user?

**Comment by lostmygithubaccount** [comment]
add the Dask extension to the Jupyter Lab session running on the headnode

**Comment by jacobtomlinson** [comment]
The extension has two components. The Jupyter server extension which needs to be installed in the Python environment, and the Jupyter Lab frontend extension which you install with the Jupyter Lab Package Manager `jlpm`.

https://github.com/dask/dask-labextension#installation
